### ISSUE TITLE
Domestication Innovation 

### ISSUE THREAD

**Issue by Uhllay** [EnigmaticaModpacks/Enigmatica8#102]
### URL

https://www.curseforge.com/minecraft/mc-mods/domestication-innovation

### Why would you like the mod added?

Because it's a fairly new mod that I think it should get more attention. It makes tamable mobs have more uses aside from what they do in vanilla and encourages players to tame mobs.

**Comment by NillerMedDild** [comment]
Looks like an excellent mod 👌
