### ISSUE TITLE
Following up in these trying times.

### ISSUE THREAD

**Issue by MrBrebby** [EnigmaticaModpacks/Enigmatica8#103]
### Describe your suggestion

I know lots of crazy shit is happening on your side of the planet right now.

Just don't want you to feel overwhelmed by all these requests you are seeing.

You are doing great work with this; but your safety comes first.  

Be strong out there man.  Lookin forward to when it all calms down.

### Why would you like this added/changed?

No changes.

Just hoping all is going well over there.

**Comment by NillerMedDild** [comment]
All is well here, thanks for the concern though :D
