### ISSUE TITLE
[Suggestion] Better Loading Screen

### ISSUE THREAD

**Issue by Lykrast** [EnigmaticaModpacks/Enigmatica8#104]
### URL

https://www.curseforge.com/minecraft/mc-mods/betterloadingscreen

### Why would you like the mod added?

* It's nice to look at
* The default progress bar spends most of its time at 95~99%, which is not helpful to know how much time is left booting, especially if that pack is gonna get as big as E2 or E6
* Memory usage is a nice way to see if the user put enough ram or not
* Looks like the colors can be changed if needed (haven't tested)

However, it slows down starting time a bit, so it's probably best to measure with or without and see if it's worth.

From my limited testing:

* Lightweight test instance, time it took to launch to menu:
  * Without: 1min10
  * With: 1min20 (+10 seconds)
* Fresh E8 install:
  * Without: 3min15
  * With: 3min30 (+15 seconds)
* It gets a little jittery when stitching one particular Blue Skies model (Dusk Chest or something), which was weird, but it worked fine all other time

**Comment by NillerMedDild** [comment]
I believe Mojang stated that they don't want people modifying the loading screen, and I'd rather not go against their wishes. I can't find the source of that info though ><

**Comment by Darkere** [comment]
Back when the logo changed, some users figured out that they could change the logo with a resource pack. Mojang then specifically disabled this feature. 

Then there are the Mojang asset guidelines which say something along the lines of "Don't use any branding that could be thought of being officially from us". 
https://account.mojang.com/documents/brand_guidelines

Which means... as long as we change the text we might be fine? Tbh I never look at the loading screen anyway.... Ding ftw.

**Comment by kil0byt3** [comment]
The source of this topic is here, and indeed it's the logo that they prefer to keep. It needs to be the default logo, not recolored. If a new loading screen retains the Mojang logo and just changes the loading bar (as this mod seems to do), I believe you are within Mojang's wishes. However, of course the final decision is up to you 😄 

https://bugs.mojang.com/browse/MC-40961

**Comment by NillerMedDild** [comment]
Alright, I guess I'll change up the colors then :P thanks for the context. 

However, I won't add this mod anyway because of the slowdown. I don't think it's worth it.
