### ISSUE TITLE
Mod Suggestion: Integrated NBT

### ISSUE THREAD

**Issue by SCLeoX** [EnigmaticaModpacks/Enigmatica8#106]
### URL

https://www.curseforge.com/minecraft/mc-mods/integrated-nbt

### Why would you like the mod added?

Integrated NBT is a QoL addon mod for Integrated Dynamics. It makes the process of drilling into deeply nested NBT easier by providing an intuitive and easy-to-use GUI. It has also been included in many prior versions of Enigmatica.

Disclosure: I am the author of this mod.

**Comment by peisach** [comment]
I second the suggestion. It is a wonderfully useful addition to Integrated Dynamics.
