### ISSUE TITLE
FTB Chunk loading not working

### ISSUE THREAD

**Issue by LarryLava** [EnigmaticaModpacks/Enigmatica8#108]
### Modpack Version

1.0.5

### Describe your issue.

Used ftb chunks to keep base loaded. It works when I move away from base, but as soon as I travel to another dimension the chunks unload after about 20 seconds.  Playing on a private creeperhost server.

### Have you modified the modpack?

Yes

### User Modifications

Disabled Dynview for memory crash issues. 

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report - I found it reported here too: https://github.com/FTBTeam/FTB-Mods-Issues/issues/200

**Comment by LarryLava** [comment]
Yes it looks similar. Although somehow in my case I can move away 5000 blocks and the chunk stays loaded and active. It's when I move to another dimension that the unloading occurs. Anyway, something's fishy, I'll experiment some more :)

**Comment by LarryLava** [comment]
So.... forceload on command line tells me 0 chunks force loaded. So apparently the ftb chunks map does not update properly. Manual forceloading using command line works as advertised and keeps chunks loaded at all times. Just a FYI for anyone having the same issue.
