### ISSUE TITLE
Light overlay

### ISSUE THREAD

**Issue by peisach** [EnigmaticaModpacks/Enigmatica8#111]
### URL

https://www.curseforge.com/minecraft/mc-mods/light-overlay

### Why would you like the mod added?

I find this mod useful for making my home safe.  If it does not cause problems or is overpowered, I think it would be nice to have.

**Comment by NillerMedDild** [comment]
We already have More Overlays Updated, which achieves the same thing but more.

**Comment by peisach** [comment]
Cool.  Thanks.
