### ISSUE TITLE
Mod Suggestion: Compat O' Plenty

### ISSUE THREAD

**Issue by BattleCh1cken** [EnigmaticaModpacks/Enigmatica8#112]
### URL

https://www.curseforge.com/minecraft/mc-mods/compat-o-plenty

### Why would you like the mod added?

All of the Biomes O' Plenty wood types can't be used to craft chests. This mod would fix that issue. It also adds compatibility with other mods like farmer's delight which is already in the pack.

**Comment by NielsPilgaard** [comment]
BoP will be replaced in v2.0.0, so this is a no :)
