### ISSUE TITLE
Mekanism + Applied Mekanistics

### ISSUE THREAD

**Issue by Uhllay** [EnigmaticaModpacks/Enigmatica8#115]
### URL

https://www.curseforge.com/minecraft/mc-mods/mekanism
https://www.curseforge.com/minecraft/mc-mods/mekanism-generators
https://www.curseforge.com/minecraft/mc-mods/mekanism-tools
https://www.curseforge.com/minecraft/mc-mods/applied-mekanistics

### Why would you like the mod added?

Because Mekanism is such a cool mod and it was recently updated to 1.18.2. The addon, Applied Mekanistics was also created recently and bridges AE2 and Mekanism nicely.

**Comment by Erysch** [comment]
Yehaaaw
