### ISSUE TITLE
The Graveyard

### ISSUE THREAD

**Issue by 0xicl33n** [EnigmaticaModpacks/Enigmatica8#117]
### URL

https://www.curseforge.com/minecraft/mc-mods/the-graveyard-forge

### Why would you like the mod added?

The graveyard structures would add more spooky places to explore and visit. The urns are an aesthetic early game chest solution. There are lots of decorative options like skeleton pieces, darker iron bars and gravestones. The ghoul mob could be tagged to drop zombie hearts from eidolon (which has yet to see a stable 1.18 release as of this suggestion) - since zombie brutes rarely drop them.  Graveyard moss spawns fog on top of it during the night which could a spooky decorative. The biomes from this mod are separate from this and I'm not sure they would fit into e8

**Comment by MrBrebby** [comment]
Honestly, had this mod in a different pack.............really excited to see this be at the very least considered for testing.
