### ISSUE TITLE
Suggestion: AE2 Things

### ISSUE THREAD

**Issue by Technici4n** [EnigmaticaModpacks/Enigmatica8#120]
### URL

https://www.curseforge.com/minecraft/mc-mods/ae2-things-forge

### Why would you like the mod added?

A ~~shameless plug~~ little mod for people who enjoy AE2, but are tired of the early game. And also a proof that other storage cell implementations are possible. :P

**Comment by NillerMedDild** [comment]
Thank you for the suggestion, I'll have a look :)
