### ISSUE TITLE
Mining Dimension/Ore Distribution

### ISSUE THREAD

**Issue by Mr-B-l-a-c-k** [EnigmaticaModpacks/Enigmatica8#121]
### Describe your suggestion

I been looking forward to the new build height since it was first introduced. My immediate thought was something like a souped up mining dim.. 

The overworld would have no ores, at all. Mining portal can be something cheap/easy. Mining dim would start at like y315, and the whole thing would be filled in (think stoneblock)

Mining deeper gets harder (not sure how to implement- different filler instead of stone?) to allow for multiple mining levels similar to e2e

### Why would you like this added/changed?

this way no hideous snake holes in the overworld, no giant world-holes, just clean stuff

mining dim could be reset if server admins wanted to, just nuke the dim file, regenerate it if needed..

**Comment by NillerMedDild** [comment]
Thanks for the suggestion :)

I don't think removing ores from the overworld is a good idea for Enigmatica, it would probably cause a fair bit of confusion, and I don't really like the concept of mining dimensions tbh. Sorry
