### ISSUE TITLE
[Alex Mobs] Kangaroo armor crash

### ISSUE THREAD

**Issue by moxycrafts** [EnigmaticaModpacks/Enigmatica8#122]
### Modpack Version

1.0.5

### Describe your issue.

Client crashes when adding armor to kangaroos (via their pouch). 

This happened first on our server, then I was able to replicate in a solo local world. 

It's been a few weeks; there's a chance I only tested using diamond armor. 

Was able to "work around" the issue on our server by using the server console to kill the kangaroo entity -- allowing the chunk to load without crashing my client.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thank you for the report, we will investigate the issue.
