### ISSUE TITLE
Missing item and ore name 

### ISSUE THREAD

**Issue by Nouhelgod** [EnigmaticaModpacks/Enigmatica8#126]
### Modpack Version

Enigmatica8-1.0.5

### Describe your issue.

Occultism raw silver / silver ore missing name string.
![image](https://imgur.com/oTLb04A.jpg)
![image](https://imgur.com/UM2vFt8.jpg)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Fixed in-dev by updating the mod, thanks 👍 
https://github.com/klikli-dev/occultism/issues/675
