### ISSUE TITLE
[Suggestion] Cloud Storage

### ISSUE THREAD

**Issue by Lykrast** [EnigmaticaModpacks/Enigmatica8#127]
### URL

https://www.curseforge.com/minecraft/mc-mods/alexs-cloud-storage

### Why would you like the mod added?

* Basically modded Ender Chests with extra flavor
* New mod so gives it some spotlight *(though Alex is not an obscure modder)*
* A few small but neat structures in the sky to loot, with the challenge of being very high in the sky with little footing
* Extra pet for Domestication Innovation
* I like it

**Comment by NielsPilgaard** [comment]
Looks very interesting :D
