### ISSUE TITLE
Beacon Overhaul

### ISSUE THREAD

**Issue by panzeson** [EnigmaticaModpacks/Enigmatica8#128]
### URL

https://www.curseforge.com/minecraft/mc-mods/beaconoverhaul

### Why would you like the mod added?

Adds more uses to the Beacon. Beacons are kind of expensive, but once made, it could be made more rewarding. With its extra effects like nutrition and long reach, I could see it easily being a really good mod.

This is what both of those effects do:
> Adds 2 new effects to the game, Long Reach, increasing interaction reach, and Nutrition, passively restoring food levels

And includes some quality of life changes to some of the vanilla effects:
> Adds a dropping mechanic to slow falling, allowing sneaking to cause a fall at normal velocity whilst still negating damage
> Adds an increased step height to jump boost, allowing the player to step up blocks instantaneously when the effect is applied

Overall, I think this mod could have some potential upon the list of end-game things to do.

**Comment by NielsPilgaard** [comment]
Sure 👍

**Comment by NielsPilgaard** [comment]
Oh, it's Fabric only.

**Comment by panzeson** [comment]
Damn, they should've specified that :C

**Comment by NielsPilgaard** [comment]
In the future, please don't suggest mods you haven't tried out first :)

**Comment by panzeson** [comment]
Apologies, every mod I've suggested that I've tried out so far (or have seen in videos) haven't been fabric, so I kinda got ahead of myself and made the suggestion, thinking it wasn't fabric.
