### ISSUE TITLE
[Mod Suggestion] Roots classic

### ISSUE THREAD

**Issue by Mang0z** [EnigmaticaModpacks/Enigmatica8#13]
### URL

https://www.curseforge.com/minecraft/mc-mods/roots-classic

### Why would you like the mod added?

A direct port of Roots classic 1.12, the pack is relatively new and lacking content (understandably so) i think roots would add some pretty cool magic to the modpack :)

**Comment by TGMax233Michael** [comment]
I'm also looking forward to adding this mod to the modpack. :3
