### ISSUE TITLE
Elemental Craft

### ISSUE THREAD

**Issue by TheDragonicSlayer** [EnigmaticaModpacks/Enigmatica8#130]
### URL

https://www.curseforge.com/minecraft/mc-mods/elemental-craft#:~:text=ElementalCraft,%3A%20infusion%2C%20binding%2C%20etc.

### Why would you like the mod added?

It's an amazing mod based around harnessing the power of elemental orbs scattered through the world. It adds a lot of useful features and is extremely fun to play with

**Comment by NielsPilgaard** [comment]
I've tried this mod a few times and didn't like it to be frank, so I'm afraid it's a no.
