### ISSUE TITLE
[Suggestion] Timber Frames

### ISSUE THREAD

**Issue by Scruffy912** [EnigmaticaModpacks/Enigmatica8#131]
### URL

https://www.curseforge.com/minecraft/mc-mods/timber-frames

### Why would you like the mod added?

A small mod that enables you to build some really cool houses\mansions.
Tested it in the 1.18.2 branch of E8 and seems to run with no problems.

**Comment by NielsPilgaard** [comment]
Looks nice, I'll have a look in-game 👍
