### ISSUE TITLE
Create Confectionery! 

### ISSUE THREAD

**Issue by TechGeekMonster** [EnigmaticaModpacks/Enigmatica8#132]
### URL

https://www.curseforge.com/minecraft/mc-mods/create-confectionery

### Why would you like the mod added?

It's Charlie and the chocolate factory in Minecraft! So this mod adds a whole bunch of chocolates to the game for automation using create. These chocolates also give buffs and it gives us more things to automate with create. Also who doesn't love chocolate?

**Comment by Shadows-of-Fire** [comment]
As nice as the art may be, that's an MCreator mod.

**Comment by TechGeekMonster** [comment]
What's a mcreator mod?

**Comment by NielsPilgaard** [comment]
We'll stear clear of this one I think, MCreator mods have had a tendency to break things in weird ways in the past, I'd rather not risk it.
