### ISSUE TITLE
Sophisticated Storage

### ISSUE THREAD

**Issue by TechGeekMonster** [EnigmaticaModpacks/Enigmatica8#134]
### URL

https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage#:~:text=Sophisticated%20Storage%20is%20mod%20that%20adds%20multiple%20tiers,upgrades%20in%20them%20to%20augment%20their%20functionality.%20Configuration

### Why would you like the mod added?

Basically Iron Chests and Metal Barrels combined with storage upgrades. It adds a whole bunch of dyeable tiered chests and barrels and upgrades that give them a whole range of uses. Its a very nice mod

**Comment by TemperedFool** [comment]
Seconded, this could make a very good replacement for Iron Chests.

**Comment by atlgeek007** [comment]
Thirded, because the current iron chests mod for 1.18.2 is garbage.

**Comment by NielsPilgaard** [comment]
Already in in-dev :D
