### ISSUE TITLE
Productive Bees

### ISSUE THREAD

**Issue by atlgeek007** [EnigmaticaModpacks/Enigmatica8#135]
### URL

https://www.curseforge.com/minecraft/mc-mods/productivebees

### Why would you like the mod added?

Seems like a fairly easy replacement for resourceful bees from 1.16 - also has built in mod compat with mek and thermal (that I've seen) if those mods are installed.

Also supports the Bumblezone out of the box, which could unblock #28

**Comment by NielsPilgaard** [comment]
I'll consider it :)

**Comment by NielsPilgaard** [comment]
I'm afraid I settled on a no, I'd rather wait for Resourceful Bees :)
