### ISSUE TITLE
Additional Create Mods

### ISSUE THREAD

**Issue by MrBrebby** [EnigmaticaModpacks/Enigmatica8#137]
### URL

https://www.curseforge.com/minecraft/mc-mods/createaddition
https://www.curseforge.com/minecraft/mc-mods/create-deco
https://www.curseforge.com/minecraft/mc-mods/steam-powered-create

### Why would you like the mod added?

There are a number of Create Mod add-ons that are quite interesting.  Crafts and Additions for example creates energy in slightly different fashions than standard Create - Alternator can create FE from SU and an Electric Motor can create SU from FE. So it works well with other FE based mods.  However, this is just a very small portion of Crafts and Additions.

Create Deco is great for adding in more life to your create contraptions, and also makes the more elaborate ones fun to decorate and have as a center piece for your builds.

Create Steam Powered adds another level of power generation and with the under ground aquifers, steam engines could be cool to make.

There are others, but they are either still in Alpha dev, or are Fabric only.  I checked to see if these are Forge or Fabric, it appears to be either Forge or both.

**Comment by NielsPilgaard** [comment]
No to all I'm afraid, same reasons as I gave in Enigmatica 6 😄 
here's the suggestion for Create Deco: https://github.com/EnigmaticaModpacks/Enigmatica6/issues/4229
Can't find the others at the moment, and I don't really wanna spend several minutes on it🤔
