### ISSUE TITLE
Super Circuit Maker! 

### ISSUE THREAD

**Issue by TechGeekMonster** [EnigmaticaModpacks/Enigmatica8#138]
### URL

https://www.curseforge.com/minecraft/mc-mods/super-circuit-maker

### Why would you like the mod added?

It's a new 1.18 mod that let's you make a lot of cool redstone contraptions. Although redstone pen does exist, this adds a few more tools to help with making redstone circuits.

**Comment by NielsPilgaard** [comment]
Thank you for the suggestion, we'll consider it :)
