### ISSUE TITLE
FTB Industrial Contraptions

### ISSUE THREAD

**Issue by TechGeekMonster** [EnigmaticaModpacks/Enigmatica8#139]
### URL

https://www.curseforge.com/minecraft/mc-mods/ftb-industrial-contraptions-forge

### Why would you like the mod added?

Its an amazing FTB tech mod that was made recently. Its similar to industrial craft in that the machines can explode, and has a whole bunch of useful tech stuff

**Comment by KacproPL132** [comment]
It looks literally as newer ic2 ^^" Love it would really want to see it added :D (And Rid is one of the devs of it!)

**Comment by GiaruDK** [comment]
But 1.16.5 have [TechReborn](https://www.curseforge.com/minecraft/mc-mods/techreborn) this mod too IC, but this mod have more content )

**Comment by atlgeek007** [comment]
TechReborn is also Fabric only.  This mod looks pretty neat though, I'm really disappointed they decided to use their own energy units.

**Comment by GiaruDK** [comment]
Oh stop, i see only now this is E8 tab. [FTB IC](https://www.curseforge.com/minecraft/mc-mods/ftb-industrial-contraptions-forge) last stable version this mod only for 1.16.5 if you need IC on E8 need use Tech Reborn.

**Comment by atlgeek007** [comment]
1.14+ for tech reborn is all fabric only.

**Comment by GiaruDK** [comment]
Shit, bad news (

**Comment by NielsPilgaard** [comment]
Mm I don't know. We'll think about it.

**Comment by TechGeekMonster** [comment]
Well, its a very fun to play with mod. It's a bit different from Mekanism. I think it would be a great addition to the pack

**Comment by NielsPilgaard** [comment]
I'll check it out :)
