### ISSUE TITLE
[Mod Suggestion] Goblin Traders

### ISSUE THREAD

**Issue by TGMax233Michael** [EnigmaticaModpacks/Enigmatica8#14]
### URL

https://www.curseforge.com/minecraft/mc-mods/goblin-traders

### Why would you like the mod added?

Just some little cute goblin traders !

**Comment by NillerMedDild** [comment]
Any idea what they offer? :)

**Comment by TGMax233Michael** [comment]
Em, just have more useful transaction than wandering trader have, and also some OP enchanted stuff. :3
