### ISSUE TITLE
FTB Quests

### ISSUE THREAD

**Issue by Gozzetto** [EnigmaticaModpacks/Enigmatica8#140]
### URL

https://www.curseforge.com/minecraft/mc-mods/ftb-quests-forge

### Why would you like the mod added?

I think that it will be helpful for newer players to have a path to follow. Also I enjoyed quests in E2E too.

**Comment by atlgeek007** [comment]
I think the next release will have this with a skeleton of quests ported over from E8 already :-)

**Comment by peisach** [comment]
The mod is already installed on the 1.18.2 branch on github. I too would  love to get the quests that someone made from E6 ported over.
