### ISSUE TITLE
AmbientSounds 5

### ISSUE THREAD

**Issue by peisach** [EnigmaticaModpacks/Enigmatica8#141]
### URL

https://www.curseforge.com/minecraft/mc-mods/ambientsounds

### Why would you like the mod added?

Because a lot of  E8 will be focused on exploration, I thought that this would be a nice addition as long as it has no performance or stability issues.  The mod does have it's own volume setting independent of the master one so people can easily reduce the effects or turn them off all together.

https://www.curseforge.com/minecraft/mc-mods/ambientsounds

**Comment by peisach** [comment]
Do you happen to know if it can be run client side only?  The reason I ask is that I run a private server with one young non-technical guest, and I try to stay with configurations that can be easily installed and updated for him.

**Comment by peisach** [comment]
Good to know. Thank you.

**Comment by NielsPilgaard** [comment]
Seeing as the focus of this pack is different from E6, I'll have a look, but no promises 😄
