### ISSUE TITLE
Applied Botanics Addon

### ISSUE THREAD

**Issue by TechGeekMonster** [EnigmaticaModpacks/Enigmatica8#144]
### URL

https://www.curseforge.com/minecraft/mc-mods/applied-botanics-addon

### Why would you like the mod added?

It's a small Applied Energistics+Botania Addon that allows a bit more easier transfer of mana and also makes the corporea system a little bit easier to use.

**Comment by NielsPilgaard** [comment]
Tempting, but.. It's a bit cheesy 😄

**Comment by theboo** [comment]
What if.... And hear me out here... No botania at all?!

**Comment by NielsPilgaard** [comment]
But Botania :'(

**Comment by TechGeekMonster** [comment]
Don't you dare Boo. A pack without Botania in my view is stupid and doesn't deserve fame. Also Botania is the greatest magic mod that's not really a magic mod. Also what do you mean cheesy Lord Niller?

**Comment by Quezler** [comment]
A modpack without botania for once would be interesting, especially for expert mode, i would love to see how stuff will be gated/mafe differently if mana isn't involved at all 🤔

**Comment by TechGeekMonster** [comment]
Never. Please dont

**Comment by TechGeekMonster** [comment]
All i mean to say, is that a kitchen sink pack feels incomplete without botania. Not true for tech based packs. Or non kitchen sink experts. Also most people dont really dive DEEP into botania cause it can get a bit overwhelming. This mod will provide a gap of breathing room.

**Comment by TemperedFool** [comment]
It's cheesy exactly because of that easier transfer of mana. Might as well make it a fluid and allow people to transfer it with fluid pipes.

As to including Botania at all, it's clearly unlikely to be removed. But Botania is beyond played out, and I agree with Boo... it's time to retire it. Let's be clear - we will not get our way ;-)

**Comment by NielsPilgaard** [comment]
Sorry but no, I don't think this fits the spirit of Botania at all. I have no plans to remove Botania either 😄

**Comment by TechGeekMonster** [comment]
Also Quezler and Tempered. I could make the same argument for Astrals Sorcery as well

**Comment by Quezler** [comment]
not having to stress about making a holorgium crystal each time it eclipses and not having to afk on vector plates to level the skill tree, progress poorly syncing between basemates & drawing tons of lines, sign me up ^-^
