### ISSUE TITLE
jet boots, More fly options

### ISSUE THREAD

**Issue by AnimusOccisor** [EnigmaticaModpacks/Enigmatica8#150]
### URL

https://www.curseforge.com/minecraft/mc-mods/jet-boots

### Why would you like the mod added?

Don't know what mods will be in the 1.18.2 pack version. Have seen that Simple Plains is in for flight. Ironjetpacks was in the 1.18.1 version and is updated. But jet boots would give an alternative for armor combinations and different immersion.

p.s. not played with it yet myself, but it is forge and updated for 1.18.2

**Comment by NielsPilgaard** [comment]
With the current mods, we have no need for this :)
