### ISSUE TITLE
Hostile Neural Networks

### ISSUE THREAD

**Issue by atlgeek007** [EnigmaticaModpacks/Enigmatica8#152]
### URL

https://www.curseforge.com/minecraft/mc-mods/hostile-neural-networks

### Why would you like the mod added?

It's an interesting method of mob farming, essentially deep learning for mob farms.  I've used it in my current 1.18.2 playthrough and it's *really* interesting IMO.

**Comment by NielsPilgaard** [comment]
I'm not a fan of the concept I'm afraid, I'd rather not add it :)
