### ISSUE TITLE
Diesel generator doesn't output power unless an entity is taking damage

### ISSUE THREAD

**Issue by BrickHead1** [EnigmaticaModpacks/Enigmatica8#153]
### Modpack Version

Enigmatica 8 1.0.5

### Describe your issue.

Was trying to set up the excavator to get some iron and the diesel generator connected to it only popped on for a second while taking in diesel fuel. Only solution to output power was if an entity was taking damage on the HV wire, it still didn't power the excavator but the generator was running.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Darkere** [comment]
An entity hitting the wire likely costs some power, which is why you are seeing this. 

Excavator is probably not properly connected. Or the excavator could be broken... We are quite a bit behind on versions.

**Comment by Quezler** [comment]
iirc it stops producing power (no sound & no animation) when it has nowhere to go, have you connected the wire to power consumers properly?

(wire zapping you uses some power, which the generator then quickly replenished)

**Comment by BrickHead1** [comment]
> iirc it stops producing power (no sound & no animation) when it has nowhere to go, have you connected the wire to power consumers properly?
> 
> (wire zapping you uses some power, which the generator then quickly replenished)

Yeah I have it connected straight into the excavator, only difference is that I'm not using an HV relay but I even tried that out and it didn't work. I had the diesel generator working fine earlier tonight and got plenty of coal but after I tried moving it with the excavator it doesn't want to work anymore.

(Testing this out in creative and I'm getting the same result)

**Comment by Quezler** [comment]
could you send a picture of your setup (with a link to this issue) in the #support channel on the enigmatica discord?
