### ISSUE TITLE
Twilight Forest

### ISSUE THREAD

**Issue by peisach** [EnigmaticaModpacks/Enigmatica8#155]
### URL

https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest

### Why would you like the mod added?

I found that another classic Minecraft mod has been ported to Minecraft 1.18.2.  I love the challenges here, as long as you limit yourself by avoiding flying up to the tops of structures.

**Comment by jlfree12** [comment]
Have they finished the mod yet? They’ve had about 10 years to add 1 boss.

**Comment by TheDragonicSlayer** [comment]
Maybe they just didn't get an idea for the final boss yet. The final boss needs to be specta

**Comment by peisach** [comment]
According to the curseforge page,they plan to finish the final castle and then continue to make more content for the mod.  They also have been integrating their materials into other mods, such as tinker's construct.  Admittedly though, the final boss has been a work in progress for a long time.

**Comment by jlfree12** [comment]
I enjoy Twilight Forest but for a kitchen sink like this the mod is pointless with it being incomplete. As a complete experience with a progression path, maybe throw it in, but TF is overdone, pointless and incomplete. It also adds a ton of loading time.

**Comment by peisach** [comment]
Well, perhaps it was a bad suggestion until there is word of them completing the final boss.

**Comment by MrBrebby** [comment]
oooo. Exciting

New release coming soon?

**Comment by fajcyk** [comment]
There is an alpha release on CurseForge:
https://www.curseforge.com/minecraft/modpacks/enigmatica8/files/3841535
