### ISSUE TITLE
Failed to Build & Launch Branch 1.18.2

### ISSUE THREAD

**Issue by FishmanDefender** [EnigmaticaModpacks/Enigmatica8#156]
### Modpack Version

commit 450914eb9f335273b83e72db6903c8c474f2ca88

### Describe your issue.

Followed the instructions in README.md under MultiMC, except I checked out branch 1.18.2 instead of develop.
I created a new MultiMC instance using vanilla 1.18.2 and added Forge version 40.1.0 (later, with a fresh instance, attempted using version 40.1.51).
Forked the project, added my fork as the remote, and fetched.
I did get the following error when trying to checkout the 1.18.2 branch:
```
$git checkout develop
error: The following untracked working tree files would be overwritten by checkout:
        config/fml.toml
        config/forge-common.toml
Please move or remove them before you can switch branches.
Aborting
```
Committed these changes to local branch master, then checked out branch 1.18.2.
ran `source InstanceSyncSetup.sh`
Then attempted to run the MC instance from MultiMC where the following errors occurred:
Forge 40.1.0 -- https://paste.ee/p/wXhli
Forge 40.1.51 -- https://paste.ee/p/7GhlJ

### Crash Report

https://paste.ee/p/wXhli

### Latest Log

https://gist.github.com/FishmanDefender/c1a4e5e9a9fea14bbbfbc7a4b9065555

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
It's likely that that particular branch is failing, it's a development branch after all 😄 I can't promise I'll have time to fix it, but I'll try.
