### ISSUE TITLE
Crafting options for Alchemical Impetus (Malum) unavailable.

### ISSUE THREAD

**Issue by FistoDaOrc** [EnigmaticaModpacks/Enigmatica8#163]
### Modpack Version

2.0.1

### Describe your issue.

The items one should be able to craft using seemingly any of the Impetus items and Spirit Crucible are not available in this version of the pack. While this still makes the Spirit Crucible an immensely powerful tool for repairing items, it removes all use for all Impetus items (save the totem of undying replacement, the Ceaseless Impetus).

Note: This is a report about being unable to use the Impetus items to craft anything other than the specific variations of other Impetus items, NOT the inability to craft Impetus items in the first place.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Seems like I've accidentally removed a ton of recipes somehow 😅

**Comment by NielsPilgaard** [comment]
Aha! It wasn't me, fixed in-dev :P
