### ISSUE TITLE
Unsure if bug, oversight, or unavailable: Currently little/no JEI implementation for Tinker's Construct.

### ISSUE THREAD

**Issue by FistoDaOrc** [EnigmaticaModpacks/Enigmatica8#164]
### Describe your suggestion

More specifically: It seems as if the majority of Tinker's Construct fluid based recipes are current unable to be viewed in JEI, mostly made a problem instead of a mild inconvenience due to the lack of alloying information elsewhere.

### Why would you like this added/changed?

Transparency of crafting processes.

**Comment by icito** [comment]
I think some of the TCon recipes are missing entirely. Should be able to craft a Smeltery Controller by pouring Molten Copper onto a Melter but that doesn't work. Also should be able to craft some of the books by solo crafting others (Such as Puny Smelting into Mighty Smelting).

**Comment by NielsPilgaard** [comment]
Hmm, I wonder what I messed up and how 😄
