### ISSUE TITLE
Placeholder textures for quest rewards.

### ISSUE THREAD

**Issue by FistoDaOrc** [EnigmaticaModpacks/Enigmatica8#165]
### Modpack Version

2.0.1

### Describe your issue.

This is likely widely known, but for the sake of having an open bug report for it...

Within the quests currently available for Enigmatica 8, there are loot chest style item rewards for many quests, most of them representing broad categories of item rewards (e.g. Farmers Delight for Food).

Potentially as a consequence of directly copying the quests from E6 to E8 with little editing beyond deleting unused questlines, the icons for these loot chest style rewards are instead replaced with the placeholder magenta-black checkerboard texture.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Heh, there was a typo in a folder name, fixed 😅
