### ISSUE TITLE
Add Spirit

### ISSUE THREAD

**Issue by CodexAdrian** [EnigmaticaModpacks/Enigmatica8#166]
### URL

https://www.curseforge.com/minecraft/mc-mods/spirit

### Why would you like the mod added?

Spirit is a soul based magic mod, built upon the soul magic added in the nether update for Minecraft. It adds highly configurable content, with soul based spawners, tools and crafting recipes. You can level up soul crystals and use them in spawners to get better, more effective mob spawners. It also adds Soul Steel tools. When empowered, these tools can use the souls in a soul crystal to perform effects, like make mobs explode on a sword swing or create a potion cloud when a soul is shot from a bow. I think it would be a fun addition to add to Enigmatica 8, tinkers construct compat is planned in the near future.

**Comment by NielsPilgaard** [comment]
Ooh looks interesting, I'll have a look 👍
