### ISSUE TITLE
Add Blocks! - A wonderful mod with a ton of new blocks

### ISSUE THREAD

**Issue by Seniorendi** [EnigmaticaModpacks/Enigmatica8#167]
### URL

https://www.curseforge.com/minecraft/mc-mods/blocksmod

### Why would you like the mod added?

Do you know the moment when you want to build a nice tower, but you don't have enough variants of blocks? Well, this mod adds a ton of new building blocks and variants. Reaching from black, to a very clean gray  to a yellow-white-ish natural color. Every of these blocks also have 5 different smoothy-types for the best building experience. 

Wonderful! You now have a ton of new blocks for your new citadel of doom. But you need lights, or? 
Blocks! also offers a ton of new lighting sources with different colors and types. Flat lamps, "tubes" or whole blocks. But the walls of your citadel are thin, how do you connect these lamps to the outlet? Well, wirelessly! You can connect all your lamps to one block wirelessly and turn every lamp on with just one lever. Isn't this *bright*?

Have a great day!

**Comment by NielsPilgaard** [comment]
Thank you for the suggestion, I'll have a look :)

**Comment by NielsPilgaard** [comment]
I checked it out and didn't quite like it to be honest, sorry but no.

**Comment by UnhappyCodings** [comment]
Hey, 

I am the Owner and Programmer of "Blocks!", would you give me some informations on what you did not like? 
Also I reworked almost my whole mod and added new Blocks and features. 
Maybe you give it a look and tell me your opinion. 

Peace out!
Unhappy

**Comment by NielsPilgaard** [comment]
> Hey,
> 
> I am the Owner and Programmer of "Blocks!", would you give me some informations on what you did not like? Also I reworked almost my whole mod and added new Blocks and features. Maybe you give it a look and tell me your opinion.
> 
> Peace out! Unhappy

Sure thing, I'll have another look and let you know 😊

**Comment by NielsPilgaard** [comment]
Well the shear amount of blocks is worrying, it'll have a noticeable impact on how much RAM the pack requires. 
That, and how similar the blocks are made it a no for me. 
It's also not obvious to me how to make the base (non-sanded) building blocks, just by looking at JEI.

I hope that's useful feedback :)
