### ISSUE TITLE
Consideration to switching over to Storage Drawers

### ISSUE THREAD

**Issue by MrBrebby** [EnigmaticaModpacks/Enigmatica8#173]
### URL

https://www.curseforge.com/minecraft/mc-mods/storage-drawers

### Why would you like the mod added?

Storage Drawers has been updated to 1.18.2 as of July 4th.  Any consideration to move from Functional Storage over to Storage Drawers?

I find the textures to be the same, but Storage Drawers is a bit more intuitive than Functional Storage.

**Comment by Gcat101** [comment]
Functional storage sucks, drawers ftw

**Comment by Darkere** [comment]
Sorry we like our storage to be functional, and not randomly void items, crash and cause other problems. 

If you have constructive criticism direct it to the mod developer, as in comparison to SD it is actually maintained. 

Also @Gcat101 this is a warning! Please only post relevant information into issues. Feel free to use up or down votes if you approve of a post.

**Comment by MrBrebby** [comment]
Copy that, didn't realize there was such a break in development with SD.

I am content with the current drawers, so not gonna moan about.
