### ISSUE TITLE
Trees not loading

### ISSUE THREAD

**Issue by CrescentFox7** [EnigmaticaModpacks/Enigmatica8#174]
### Modpack Version

2.0.1

### Describe your issue.

My friend is hosting a server with no issues popping up but trees such as the cherry trees and maple trees will grow but no to little blocks spawn and act like when you break a block too fast. The blocks aren't there and when you try to move to where the blocks are it freezes you in place. Also when one person breaks the trees the other players can see them now but aren't actually there.

### Have you modified the modpack?

Yes

### User Modifications

We added the create 5.0, flywheel 0.6.3, and create additions 20220709a

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by NielsPilgaard** [comment]
Do you know if this also occurs without Create + dependencies and addons?

**Comment by random001us** [comment]
i also have this issue with many tree types on unmodified E8 server
reloading the area (going far enough away, relogging, going to another dimension and back, ect.) makes the trees appear

**Comment by random001us** [comment]
don't know if its related but waystones placed by other people are also invisible until reloaded or you try to place a block on the spot they are.

**Comment by NielsPilgaard** [comment]
Should be fixed in the next version, I added the mod [Connectivity](https://www.curseforge.com/minecraft/mc-mods/connectivity) which resolves this. At least it did on 1.16.5 😄
