### ISSUE TITLE
[Missing Mod?] Sophisticated Storage

### ISSUE THREAD

**Issue by FistoDaOrc** [EnigmaticaModpacks/Enigmatica8#175]
### URL

https://www.curseforge.com/minecraft/mc-mods/sophisticated-storage

### Why would you like the mod added?

Didn't know how better to do this; This mod seemed to be accepted and set for this most recent release (2.1.0) according to the issue tracker, but it never got added.

This is a purposeful duplicate, mostly to ask if (like the Tetra situation) it was left out on purpose or by accident.

**Comment by NielsPilgaard** [comment]
D'oh, I'll get that added 😅
