### ISSUE TITLE
3 tin version

### ISSUE THREAD

**Issue by AnimusOccisor** [EnigmaticaModpacks/Enigmatica8#176]
### Modpack Version

2.1.0

### Describe your issue.

Bug or feature, but 3 different tin versions

raw tin from mekanism
tin chunk from FTB industrial contraptions
raw tim from thermal

[edit] also multiple lead version
raw lead from immersive
raw lead from thermal
lead chunk ftb industrial contraptions

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Thanks for the report.

Sorry about that, I thought I got them all 😅

**Comment by Kanzaji** [comment]
There are also 2 different types of Silver @NielsPilgaard 😅 
immersiveengineering:raw_silver
thermal:raw_silver

**Comment by NielsPilgaard** [comment]
Caught that one in the config already 👍 thanks!

**Comment by NielsPilgaard** [comment]
Oh lord, FTB:IC doesn't allow turning off it's oregen I think

**Comment by NielsPilgaard** [comment]
Alright, think I got them all >_<
