### ISSUE TITLE
You can dupe DeepResonance Luiquid Crystal with use of Purifier

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica8#178]
### Modpack Version

2.0.1

### Describe your issue.

After you purify your Crystals from one tank to another, and then you break the upper tank in your setup, you can get another batch of what was in that tank before purification.
Its hard for me to explain, so here is the video :D
https://youtu.be/JKhhBw7zF7c

### Have you modified the modpack?

Yes

### User Modifications

I updated JEI because shipped one was broken.

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Kanzaji#0621

**Comment by Kanzaji** [comment]
Thats something new with that Discord Username. Neat! (To not bother with different nicknames etc. .Kanzio! is me :D The same pfp as here)

**Comment by NielsPilgaard** [comment]
Thanks for the report - Would you mind relaying to the Deep Resonance issue tracker yourself? https://github.com/McJtyMods/DeepResonance/issues

**Comment by Kanzaji** [comment]
@NielsPilgaard There is actually no need with a bit more of reasearch, looks like its fixed in the latets update 😄 
https://github.com/McJtyMods/DeepResonance/issues/304

**Comment by NielsPilgaard** [comment]
Oh excellent :P
