### ISSUE TITLE
[Mod Suggestion] Scannable

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica8#179]
### URL

https://www.curseforge.com/minecraft/mc-mods/scannable/files/all?filter-game-version=2020709689%3A7498

### Why would you like the mod added?

This is really useful and present in other Enigmatica modpacks mod, used for scanning for ores blocks mobs etc. You already know that mod and I think it should be added to E8 as well :D

**Comment by NielsPilgaard** [comment]
Sure thing.

**Comment by panzeson** [comment]
I feel like this makes the modpack too easy though, unless the recipe for the scanner was modified in a way that makes it useful endgame

**Comment by Kanzaji** [comment]
Well right it is hella cheap, but changing recipes isn't a problem :D
However as a sink pack, I don't think its necessary, but thats for Niller to decide 😄

**Comment by NielsPilgaard** [comment]
I think it's fine as-is to be honest, we're not aiming for difficulty here.
