### ISSUE TITLE
[Mod Suggestion] Voluminous Energy

### ISSUE THREAD

**Issue by Mang0z** [EnigmaticaModpacks/Enigmatica8#18]
### URL

https://www.curseforge.com/minecraft/mc-mods/voluminous-energy

### Why would you like the mod added?

this mod is very similar to tech reborn and more tech is always welcome right? it adds new power gen methods, naturally spawning oil deposits and multiblocks 
(theres also https://www.curseforge.com/minecraft/mc-mods/industrial-reborn just incase this one doesnt work or something)

**Comment by NillerMedDild** [comment]
Approved for the time being, I can't promised it'll remain in the pack in the long run though :)

**Comment by NillerMedDild** [comment]
I've changed my mind, as I have a bad feeling about this mod 😅
