### ISSUE TITLE
[Mod Suggestion] Open Block Elevator, everyone needs those!

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica8#181]
### URL

https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator/files

### Why would you like the mod added?

Already used in every Enigmatica modpack. They are on Beta so not sure if its exactly stable, but thats for yours decision ^^"

**Comment by NielsPilgaard** [comment]
> Already used in every Enigmatica modpack.

It's not 😄 

We use Travel Anchors instead, same functionality + more.

**Comment by Kanzaji** [comment]
Well technically true about Travel Anchors, but I know they are a thing in E6 😅
Anyway no is a no. Should I close it ^-^"?

**Comment by NielsPilgaard** [comment]
Oh so it is, my bad 😅 I really ought to remove it then.
