### ISSUE TITLE
Tetra tools cannot excavate

### ISSUE THREAD

**Issue by pekudzu** [EnigmaticaModpacks/Enigmatica8#182]
### Modpack Version

2.1.0

### Describe your issue.

Tetra tools are unable to excavate ores using FTB ultimine, with text reading 'FTB Ultimine is /not active/' when the keybind is pressed.
![image](https://user-images.githubusercontent.com/98293751/180136881-8d91f94c-96a9-4bd5-ab5f-487ae3b5a0dc.png)
Here is an image of the F3+H data on the tools, which i believe indicates that the lack of a forge:tools item tag is the culprit.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by pekudzu** [comment]
An image of a vanilla stone axe, too.
![image](https://user-images.githubusercontent.com/98293751/180137082-f46ff9f9-5ce4-44ac-b67f-954bf590f1a1.png)

**Comment by mickelus** [comment]
Could it be that it's missing the tools tag?

**Comment by NielsPilgaard** [comment]
FTB Ultimine is set to only work with tools, I'm guessing it can't detect the durability on Tetra tools for some reason. Adding the tag hopefully fixes this 👍 

Config:
```toml
# Require damageable tools or items added to ftbultimine:tools tag to ultimine.
# Default: false
require_tool: true
```

**Comment by NielsPilgaard** [comment]
It didn't work sadly. @MaxNeedsSnacks halp?

**Comment by MaxNeedsSnacks** [comment]
Didn't write that bit, quick search tells me it either needs to be an instance of `TieredItem` or be damageable, which I'm assuming modular tools like Tetra and TCon don't use vanilla's damage for obvious reasons.

That said, you can add it to the `ftbultimine:included_tools` tag to force them to work, apparently that tag behaves different when require_tool is enabled

**Comment by NielsPilgaard** [comment]
I'll try that, thanks 👍

**Comment by NielsPilgaard** [comment]
Still doesn't work @MaxNeedsSnacks :( 

I added the following tags:

![image](https://user-images.githubusercontent.com/21295394/180616980-ba6eb294-8531-433a-a78b-711c96d1a3d6.png)

**Comment by MaxNeedsSnacks** [comment]
Can you put this on the FTB mod issues tracker? Might have to defer to Mikey since I don't have much free time atm

**Comment by NielsPilgaard** [comment]
Done, thanks for your time anyhow :D

**Comment by PopcraftReal** [comment]
It's not just with Tetra Tools but also with Tinker's Tools. Should I make it as another issue?

**Comment by NielsPilgaard** [comment]
No thank you 👍
