### ISSUE TITLE
[Mod Suggestion] Advanced Peripherals for CC

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica8#183]
### URL

https://www.curseforge.com/minecraft/mc-mods/advanced-peripherals

### Why would you like the mod added?

Its really useful and adding a lot of functionality addon for CC, already in E6. I know that people that use CC would love this added (like me :D)

**Comment by Quezler** [comment]
wasn't this one already suggested/accepted for e8?

**Comment by Kanzaji** [comment]
I mean, maybe? However its still not in the pack ^^"

**Comment by Quezler** [comment]
ah, guess niller forgot that one too then (#18)

**Comment by Kanzaji** [comment]
Well probably 😄

**Comment by NielsPilgaard** [comment]
Yeah I probably forgot xD

**Comment by NielsPilgaard** [comment]
Modpack updates between minor Minecraft version updates are.. just awful :P

**Comment by Quezler** [comment]
elaborate?

**Comment by NielsPilgaard** [comment]
I have to start from scratch with jars, re-adding every mod manually through the CurseForge App, usually.
