### ISSUE TITLE
Two Logs for 16 sticks

### ISSUE THREAD

**Issue by PopcraftReal** [EnigmaticaModpacks/Enigmatica8#184]
### Describe your suggestion

I suggest to have a recipe like in E6 which you have two logs vertically two craft 16 sticks.

![image](https://user-images.githubusercontent.com/72920999/180607206-b013bc8b-dbe6-4e39-b503-b128bef32688.png)

### Why would you like this added/changed?

It's just a QoL / convenient thing where you can craft 16 sticks using two logs instead of two logs -> eight planks -> 16 sticks.

**Comment by NielsPilgaard** [comment]
Sure thing 👍
