### ISSUE TITLE
server pre gen tool

### ISSUE THREAD

**Issue by AnimusOccisor** [EnigmaticaModpacks/Enigmatica8#185]
### URL

https://www.curseforge.com/minecraft/mc-mods/world-pre-generator

### Why would you like the mod added?

Added in manual and been generating since last night! But is a useful tool for those that just want easy mode or can just handle copy/paste a command in a console.

Hopefully it fixes the chunk issues I have on a hosted server with 6Gigs allocated.

**Comment by NielsPilgaard** [comment]
Forge already has a command for pregenning :)

**Comment by AnimusOccisor** [comment]
Was looking for it , but failed to find it :x

**Comment by NielsPilgaard** [comment]
`/forge pregen` iirc
