### ISSUE TITLE
Bug: Occultism silver not generating and initial ritual does not accept other silver types.

### ISSUE THREAD

**Issue by ClaymooreEOC** [EnigmaticaModpacks/Enigmatica8#187]
### Modpack Version

2.1.0

### Describe your issue.

The first ritual in occultism (summon foliot crusher) requires raw iron, copper, gold and silver.
The silver required must be from occultism.
This type of silver cannot be found or crafted.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

JennieMoore#0280

**Comment by NielsPilgaard** [comment]
Thanks for the report, fixed in-dev :)
