### ISSUE TITLE
Many missing quest trigger items

### ISSUE THREAD

**Issue by e-SonOfAnder** [EnigmaticaModpacks/Enigmatica8#188]
### Modpack Version

2.1.0

### Describe your issue.

The quest book has a great many quests which are currently broken because there are no valid items for the quest reward trigger. A couple of specific examples:

Equipment -> Tetra -> Swords
Logistics -> Storage -> Iron Chests

Just glancing through the other chapters of the quest book, I can see a large number of these quests where the trigger condition shows the purple box with a question mark in it indicating there are no valid items.

![2022-07-24_12 18 56](https://user-images.githubusercontent.com/4420108/180662617-ceb13966-3367-4f9a-8e6a-79babe8b7b12.png)
![2022-07-24_12 18 27](https://user-images.githubusercontent.com/4420108/180662620-58d7c82a-6b7c-4c67-8113-94a57bcf30a3.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by Kanzaji** [comment]
@NielsPilgaard Sorry for the ping, but I think this is fixed in 2.2.1 😅 (Ofc except Create nad Ars, but those are marked as WIP so :D)
