### ISSUE TITLE
Looting enchant on Tetra sword

### ISSUE THREAD

**Issue by AnimusOccisor** [EnigmaticaModpacks/Enigmatica8#191]
### Modpack Version

2.1.0

### Describe your issue.

Looting is not a valid enchant for Tetra weapons it seems.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by mickelus** [comment]
I'm also getting this in 2.1.0 but I'm unable to reproduce it with just tetra. Which enchantments go where depends on the EnchantmentCategory of the enchantment in 1.18, might be that some mod has somehow changed the category for looting. Tags can be used to further tweak how the enchantments can be applied and tagging looting with `tetra:additions/edged_weapon` (and `tetra:additions/edged_weapon` to get it to work for hammers) seems to fix the issue, want me to PR the fix?

**Comment by NielsPilgaard** [comment]
Yes please 😊

**Comment by AnimusOccisor** [comment]
Checked both merged json files, they are the same as in the push, but cannot put looting on a sword. 
So it's still broken ??

**Comment by mickelus** [comment]
Could have sworn it worked when I made the PR 😅. I've gotten similar bug reports where players are also running ensorcellation, ensorcellation replaces the category for some vanilla enchantments which causes them to not match properly with how tetra checks which enchantments can go where.

**Comment by NielsPilgaard** [comment]
We do have Ensorcellation 😅

**Comment by NielsPilgaard** [comment]
Works just fine in-dev 👍

**Comment by mickelus** [comment]
Fixed up looting, fire aspect and knockback not working when ensorcellation is installed in 4.9.4!
