### ISSUE TITLE
larger and faster  crafters for refinend storage

### ISSUE THREAD

**Issue by AnimusOccisor** [EnigmaticaModpacks/Enigmatica8#193]
### URL

https://www.curseforge.com/minecraft/mc-mods/extrastorage

### Why would you like the mod added?

It was also in the old pack. I'm hitting limits for my recipes with only 9 per crafter!

**Comment by Darkere** [comment]
...Do we not have https://www.curseforge.com/minecraft/mc-mods/rebornstorage yet?

**Comment by AnimusOccisor** [comment]
> ...Do we not have https://www.curseforge.com/minecraft/mc-mods/rebornstorage yet?
> 
> > **[Attention Required! | Cloudflare](https://www.curseforge.com/minecraft/mc-mods/rebornstorage)**

Had to double-check, No! And by the looks of it that is a multiblock for crafting recipes, not for automating machinery.

**Comment by Darkere** [comment]
Yes. Usually only crafting recipes are a problem because of crafter chaning https://refinedmods.com/refined-storage/wiki/crafter.html#chaining

**Comment by AnimusOccisor** [comment]
Forgot about the chaining, :x Both mods would work, but at this point would be only QoL as it can be done with current mod.

Would like a Yay but expect a Nay :)

**Comment by NielsPilgaard** [comment]
Gonna be a nay this time around :)
