### ISSUE TITLE
Silver is missing processing recipes in mekanism 

### ISSUE THREAD

**Issue by AnimusOccisor** [EnigmaticaModpacks/Enigmatica8#194]
### Modpack Version

2.1.0

### Describe your issue.

Silver is missing the refining processing recipe in mekanism. there are more "metals" missing but those are semi mod specific. 
Like: Bauxite >> Aluminium, zinc, nickel But those are only used by those "specific" mod. 

Silver is used in a lot of other mod recipes.
As an example: Occultism, iron jetpacks, thermal series, industrial foregoing, immersive engineering.
In my opinion, should all the general ores be processable by a mod!

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by PopcraftReal** [comment]
Well, it's not part of the mod Mekanism in the first place. So it shouldn't be a bug, it's more of a suggestion.
