### ISSUE TITLE
Backup

### ISSUE THREAD

**Issue by NickyMB** [EnigmaticaModpacks/Enigmatica8#195]
### Modpack Version

2.1.0

### Describe your issue.

If world name has special char like ąęś etc. backup gives an error:
An unexpected error occurred trying to execute that command

### Latest Log

https://gist.github.com/NickyMB/4d5da61ffc7a49f515cf380d38e283d8

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Szef#2794

**Comment by Gcat101** [comment]
Maybe you should submit this issue to FTBTeam/FTB-Mods-Issues?
