### ISSUE TITLE
game crash because of AIOT 

### ISSUE THREAD

**Issue by BlackPhoenixML** [EnigmaticaModpacks/Enigmatica8#196]
### Modpack Version

2.1.0

### Describe your issue.

Whenever i right clicked a block with the AIOT that isnt interactable with, like normal wood planks, the game crashed. if i clicked on logs, they were stripped as normally. But when i clicked on a stripped log, game crashes again and only with AIOT in hand. i tried it with wooden and stone AIOT

### Crash Report

https://gist.github.com/BlackPhoenixML/835d35bac9a40d9accb28df306b05ba7

### Latest Log

https://gist.github.com/BlackPhoenixML/7021d5f98fd38550fae5f219c4f26a5c

### Have you modified the modpack?

Yes

### User Modifications

Added Minecolonies with its dependencies Multipiston and Domum Ornamentum

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

кαт#4114

**Comment by MelanX** [comment]
Here the issue on mods repo: https://github.com/MelanX/VanillaAIOTs/issues/2
Already fixed :)
