### ISSUE TITLE
Create gantry not working with Entity Culling

### ISSUE THREAD

**Issue by dobbylego** [EnigmaticaModpacks/Enigmatica8#197]
### Modpack Version

2.1.0

### Describe your issue.

The Create mod gantry is not rendering, and then catching up all at once. Its particularly bad if you are riding on the gantry while not looking at it. You stand completely still, and the second you render the gantry it suddenly loads. I tried adding create:gantry_carriage and create:gantry_shaft to the blockEntityWhitelist of Entity Culling but it had no effect. Removing the mod fixes the issue so it looks like it just needs a whitelist line added but I do not know what it would be called. 

### Crash Report

N/A

### Latest Log

N/A

### Have you modified the modpack?

Yes

### User Modifications

Removed Entity Culling to make the gantry render while moving.

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

IronWill#7117

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by NielsPilgaard** [comment]
I couldn't reproduce the issue, but tried fixing it by whitelisting the Gantry Carriage as an entity
