### ISSUE TITLE
IE Concrete & TS Slag Conflict

### ISSUE THREAD

**Issue by SirJamesGhost** [EnigmaticaModpacks/Enigmatica8#198]
### Modpack Version

Enigmatica 8 2.1.0

### Describe your issue.

The Immersive Engineering Concrete recipe involving slag, which produces 12 concrete, does not recognize Thermal Series Slag (which replaces IE Slag as an output from machines) as a valid ingredient. 
![image](https://user-images.githubusercontent.com/31163772/181934285-8dc4912a-62bd-4ae5-b44b-9ba03bea926f.png)
![image](https://user-images.githubusercontent.com/31163772/181934295-381783ff-f7f6-42f7-ae5a-e81844f0dc74.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

CIockworkGhost#2243

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.
