### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by scone32** [EnigmaticaModpacks/Enigmatica8#200]
### Modpack Version

2.1.0

### Describe your issue.

Lots of items in the Quest book for rewards and triggers are missing items.

![image](https://user-images.githubusercontent.com/76638734/182529914-4a76736b-a218-4b1a-b1a7-4e071306fbd9.png)
![image](https://user-images.githubusercontent.com/76638734/182530079-830f4d93-ef6a-4e8c-8da8-a0f47e83b8c9.png)
![image](https://user-images.githubusercontent.com/76638734/182529944-8dafdf0d-a411-4376-9f87-e260f00395db.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by scone32** [comment]
Appears to be primarily Iron Chest Mod items, Pretty Pipe mod items, and copper chunks for some reason after a closer look?

**Comment by Quezler** [comment]
something something known issue, quests were copied from enigmatica 6 and not all mods there were quests for are in enigmatica 8, so everything that is missing renders al black and purple.

**Comment by Kanzaji** [comment]
Also copper chunk is now from Vanilla so that's why

**Comment by NielsPilgaard** [comment]
I think @Kanzaji fixed all or at the very least most of these :)
