### ISSUE TITLE
Please add Powah Rearchitected

### ISSUE THREAD

**Issue by AbsorbingSafe11** [EnigmaticaModpacks/Enigmatica8#207]
### URL

https://www.curseforge.com/minecraft/mc-mods/powah-rearchitected

### Why would you like the mod added?

Powah was a very good mod for 1.16 and this newer version keeps all of the same features, so players can have more options for generating power again. (it is for Forge and Fabric, so make sure the correct file is used)

**Comment by NielsPilgaard** [comment]
Thank you for the suggestion, I'll have a look :)
