### ISSUE TITLE
FTB Ultimine Tag Issue

### ISSUE THREAD

**Issue by PopcraftReal** [EnigmaticaModpacks/Enigmatica8#208]
### Modpack Version

2.1.0

### Describe your issue.

So I changed the FTB Ultimine config to "require_tools:false" and I added the files adding tags "ftbultimine:tools" and "ftbultimine:included_tools" to the tools. Since then I can't use the FTB Ultimine at all. But when I get rid of the tags, it worked again.

### Have you modified the modpack?

Yes

### User Modifications

- FTB Ultimine config to "require_tools:false
- Adding tags "ftbultimine:tools" and "ftbultimine:included_tools" to the tools through KubeJS

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Popcraft#4935

**Comment by Quezler** [comment]
after a quick look at the code, it appears that even without `requires tool` the whitelist gets used if there are tagged items:
https://github.com/FTBTeam/FTB-Ultimine/blob/9732734f114f85603d8a7dec67728af2047b1829/common/src/main/java/dev/ftb/mods/ftbultimine/FTBUltimine.java#L164

**Comment by PopcraftReal** [comment]
Oh true. What's the point of checking Require Tools if you're gonna use it anyway XD

**Comment by Quezler** [comment]
i am not exactly sure what the reasoning behind it was, didn't feel like going down the blame rabbit hole (through the port),
i can only imagine that for some reason they wanted a setting to only enable it for items with durability, someone should ask.

**Comment by NielsPilgaard** [comment]
Well that's weird, should be fixed for next update though 👍
