### ISSUE TITLE
Please blacklist the consumable books from Blue Sky for Akashictome (it vanishes the book tome!)

### ISSUE THREAD

**Issue by mjevans** [EnigmaticaModpacks/Enigmatica8#209]
### Modpack Version

E8 2.1.0

### Describe your issue.

Please blacklist the consumable books (At least the Adventurer's guide obtainable via the standalone villager trade for a normal book) from Blue Sky for Akashictome; right clicking to open consumes the entire tome.

### Have you modified the modpack?

Yes

### User Modifications

World generated with the github Development branch's single ore type tweaks (cherry picked).  This shouldn't have any relation to the behavior of the books.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NielsPilgaard** [comment]
Yikes, fixed in dev :)
