### ISSUE TITLE
The Mighty Architect has been updated to 1.8.2

### ISSUE THREAD

**Issue by Moonwolf287** [EnigmaticaModpacks/Enigmatica8#210]
### URL

https://www.curseforge.com/minecraft/mc-mods/the-mighty-architect

### Why would you like the mod added?

It seems to have been in before the update and I want it back.

**Comment by NielsPilgaard** [comment]
Thanks for the suggestion, but I'd rather have people add it themselves, as I believe it isn't widely used.
