### ISSUE TITLE
Iron Jetpacks are confusing FTB quests, allowing to any of the jetpacks trigger quest.

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica8#213]
### Modpack Version

2.1.0 Develop as 15.08.2022 (#3d33d41)

### Describe your issue.

Iron jetpacks use one item for all jetpacks, and use a tag with ID to change tiers for it. Even tho that ID is specified in quest task, any jetpack triggers it:
![obraz](https://user-images.githubusercontent.com/60540476/184591742-4fd91dff-20be-4314-83c6-4e467ac8bd08.png)
![obraz](https://user-images.githubusercontent.com/60540476/184591765-1ae1af8d-a87e-4584-aba1-a33b9175b22e.png)

### Have you modified the modpack?

Yes

### User Modifications

Working on fixing quests and all changes from develop.

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Kanzaji#0621 (Note, I have (offline till 28.08) in nick, so search More High Asylum Patient on Enigmatica Server :D (Or ask Darkere)

**Comment by NielsPilgaard** [comment]
I think you'll have to use a Weak NBT Filter from the Item Filters mod to get it to work correctly.

**Comment by NielsPilgaard** [comment]
Perhaps you can use the crafting ingredients instead?

**Comment by Kanzaji** [comment]
Good idea actually. This will prevent quests from activating to early, but giving access to recipes :D Alrighty thx
(But this still counts as a bug I think, as it should work normally but doesn't want to)

**Comment by Kanzaji** [comment]
Okay so it turnes out crafting ingredients have the same problem, those Iron Jetpacks are gonna be wonky 😅

**Comment by Kanzaji** [comment]
Did get wonky work-around, that doesn't show error when trying to check recipe, but anyways l reported it to FTB Quests
https://github.com/EnigmaticaModpacks/Enigmatica8/issues/211#issuecomment-1215911325_

Note: I found that issue is known bug, so just waiting for a fix [FTBTeam/FTB-Mod-Issues/#182](https://github.com/FTBTeam/FTB-Mods-Issues/issues/182)
