### ISSUE TITLE
Just Enough Calculation

### ISSUE THREAD

**Issue by PopcraftReal** [EnigmaticaModpacks/Enigmatica8#215]
### URL

https://www.curseforge.com/minecraft/mc-mods/just-enough-calculation

### Why would you like the mod added?

Do you know what is the most convenient thing in crafting? Having a recipe calculator in Minecraft. Introduce this mod, it will allow you to store recipes and do calculations with it without pausing Minecraft and solve equations :D

**Comment by NielsPilgaard** [comment]
I don't think this would be used very much, and personally don't really like it, so no :)
