### ISSUE TITLE
[DEVELOP] JEI on update 240 returns known bug with Tinkers and Create recipes not showing up

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica8#217]
### Modpack Version

2.1.0 Develop (#3d33d41)

### Describe your issue.

https://github.com/EnigmaticaModpacks/Enigmatica8/issues/211#issuecomment-1216281231

JEI was updated in develop to 240 from 232, but it has old bug in it with half of Tinkers and Create Recipes not showing up. #168 #164 

https://user-images.githubusercontent.com/60540476/184828242-92a19fe4-f38e-4711-ab26-ed737109822d.png

I did some experimenting, tried 226 but it wasn't compatible, but issue seems to be fixed by downgrading JEI back to the state from 2.1.0 -> 232

https://user-images.githubusercontent.com/60540476/184828337-5e7043db-a6ed-4308-9006-be03293fc20b.png

### Have you modified the modpack?

Yes

### User Modifications

Playing on Develop, added a lot of new tags and other changes, Working on #

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Kanzaji(Offline till 28.08)#0621 (Ask Darkere / Motoko if there is a problem finding me :D)

**Comment by NielsPilgaard** [comment]
Works just fine now, no idea how :P
