### ISSUE TITLE
Add twilightforest:mazestone to break_blacklist from ars noveau

### ISSUE THREAD

**Issue by SevenChords** [EnigmaticaModpacks/Enigmatica8#219]
### Describe your suggestion

add the mazestone from twilight forest (twilightforest:mazestone) to the blacklist for blocks that can't be broken by ars noveau break spells

### Why would you like this added/changed?

mazestone is intended to be only breakable using the mazebreaker pickaxe, right now ars noveau spells using the break glyph can insta break mazestone without penalties.

**Comment by NielsPilgaard** [comment]
Will do, thanks 😊
