### ISSUE TITLE
Missing Mod? (Applied Mekanistics)

### ISSUE THREAD

**Issue by IkarusFalling** [EnigmaticaModpacks/Enigmatica8#221]
### Modpack Version

2.1.0

### Describe your issue.

Dear Enigmatica Team

As I was exploring the Available Addons for AE2 I noticed that 
Applied Mekanistics (https://www.curseforge.com/minecraft/mc-mods/applied-mekanistics) was missing which I found strange as it was approved of in this Ticket (https://github.com/EnigmaticaModpacks/Enigmatica8/issues/115) to be added to the pack?
If I misjudged something feel free to close the ticked I just wanted to write this as it seems that it got forgotten (Did not want to make a mod suggestion as it was already suggested and accepted as far as I can tell (if that was wrong please inform))

Sincerely Ikarus Falling

### Crash Report

Does not apply 

### Latest Log

Does not apply as far as I know?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
My bad 😅
