### ISSUE TITLE
Crafting tweaks

### ISSUE THREAD

**Issue by MaddoScientisto** [EnigmaticaModpacks/Enigmatica8#223]
### URL

https://www.curseforge.com/minecraft/mc-mods/crafting-tweaks

### Why would you like the mod added?

It used to be in older versions and was never listed as removed also it's, I dare say, an essential mod.

**Comment by NielsPilgaard** [comment]
I don't really like it tbh 😄 since it's clientside only it's luckily simple to add to your instance of the pack 🙂

**Comment by MaddoScientisto** [comment]
well you see, the funny thing is that I added it myself and the map got corrupted or something and was stuck permanently crashing

**Comment by NielsPilgaard** [comment]
I don't see how those things can be related to be honest.

**Comment by MaddoScientisto** [comment]
I was going to say that the problem is that if I add it myself then it's an unsupported case in regards to the modpack so I get no support, while if it's officially in then I'd get support because it's a supported case.

However it turned out to be a completely unrelated issue and didn't happen on other maps so arguing further is completely useless for me, sorry for wasting time

**Comment by NielsPilgaard** [comment]
Ah okay, valid point about support :)
