### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by NickyMB** [EnigmaticaModpacks/Enigmatica8#224]
### Modpack Version

2.2.0

### Describe your issue.

When I try to put framed diamond chest (i guess) game crashes

### Crash Report

<script src="https://gist.github.com/NickyMB/59fc4116b1230c95b61ae0df311c40f5.js"></script>

### Latest Log

<script src="https://gist.github.com/NickyMB/888cf32210abfb8f94b737d60b0ce1f6.js"></script>

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Szef#2794

**Comment by Darkere** [comment]
The latest.log shows a crash rendering the tooltip of the akashic tome inside an AE system. Not sure if you got the  right one?

**Comment by NickyMB** [comment]
Maybe it is that arkashic tome. I don't know. I wrote how it looked like for me. How i can take it out without crash?

**Comment by Darkere** [comment]
you might be able to use an exporter to export the item out of the system with a fuzzy card. Do not look at the tooltip of the item.

**Comment by Kanzaji** [comment]
I... did forget that akashic tome is broken, was meant to fix it but I wasn't fast enough :sweat_smile: Gonna work on fix today.
So it is possible crash is caused by akashic tome.

**Comment by Kanzaji** [comment]
Wait I should actually ask it before actually assuming that is the problem.
@NickyMB is that Akashic Tome your own one? Or did you take WIP one from quest reward?
If the quest one, it is known to actually cause a crash, and should not be used for now.

**Comment by NickyMB** [comment]
I got it from quest. I fixed it with fast deleting that item
