### ISSUE TITLE
New Apotheosis Update breaks custom loot boxes.

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica8#225]
### Modpack Version

2.2.0

### Describe your issue.

*This bug report is mostly just to be here, so people will know that this is a bug, not a feature ^^"*

So I did port loot tables for quests recently, now I came back for fixing quests, but I did update my branch fully and this started happening: (Context: I claimed I think 5/6 loot boxes from PNC:R, got everything from them nomally and...)

![obraz](https://user-images.githubusercontent.com/60540476/185803478-56a8d0a9-93a4-4174-8cb1-515d5026c200.png)

I was talking a bit with dev of Apotheosis, and I know the cause of the issue.
New update of Apotheosis runs as global loot table modifier for any loot table `chest`, the same as our loot boxes ^^"
I am working on a fix, not sure how long it could take, but with this fix will come Quest Rework part 2 as I promised :D

### Have you modified the modpack?

Yes

### User Modifications

Running on Dev version of the modpack, that isn't much atm. Changed a bit quests.

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Kanzaji(Offline till 28.08)#0621 (Ask Darkere / Motoko if there is a problem finding me :D)

**Comment by NielsPilgaard** [comment]
Ooh unintended feature, cool!

**Comment by Kanzaji** [comment]
*It's a feature, not a bug 😂*

**Comment by hofmannk69** [comment]
Not sure if this has anything to do with this issue or not and if it doesn't please ignore/delete this post.  I found a graveyard from the graveyard mod when all the coffins were looted I ended up with a complete set of apotheosis netherite armor (also more than a full set of apotheosis diamond armor) and more than a double chest of those new apotheosis gems that you can add to slots along with a ton of other stuff.  The graveyards are also too common.

**Comment by NielsPilgaard** [comment]
I'd say that is related, thank you :) I'll look into tweaking graveyards.

**Comment by hofmannk69** [comment]
It appears that all the loot boxes contain alot of apotheosis loot, I have now about 4 or 5 netherite pick axes and another chest full of the apotheosis gems.

**Comment by Kanzaji** [comment]
Quest loot boxes are fixed already :D But to change rarity of the loot, we will need (I think) wait for apotheosis update with config for that. As for now it's ~55% to add loot to loot table starting at 'chests'

**Comment by Kanzaji** [comment]
Any more changes on this issue or we could close it 😄?
