### ISSUE TITLE
Killing Shulker while bullet is in midair causing Null Pointer Exception while ticking entity

### ISSUE THREAD

**Issue by IcarusWhite** [EnigmaticaModpacks/Enigmatica8#230]
### Modpack Version

2.2.0

### Describe your issue.

While making a Shulk-Me-Not (botania) farm, caused a Null Pointer Exception.
This setup uses a Heisei Dream flower to make the Shulkers fight each other.
However, when I killed one, its bullet went on to hit another one (I think?), and caused a Null Pointer Exception.
Afterwards, attempting to reload the world lead to the error that I have attached, and another Null Pointer Exception.

I will attempt to remove erroring entities and reload the world.
(Update: using NBTedit to remove the single shulker bullet worked!)

### Crash Report

https://gist.github.com/IcarusWhite/d0d8167933d33b807b81fd80e0bf83c7

### Latest Log

https://gist.github.com/IcarusWhite/901f5a1920f1c04c28fa8914e63cbfda

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Rastaban_TzW#0176

**Comment by IcarusWhite** [comment]
An addition:
Shortly after successfully reloading the world, a shulker hit me with a bullet, after it had been "eaten" by the Shulk-Me-Not.
Error report and latest log are located at the link.

https://gist.github.com/IcarusWhite/a8c888808525e7101f2422cc93c8b32e

**Comment by NielsPilgaard** [comment]
Thanks for the report - This has been fixed in Apotheosis 5.5.0, which we'll update to shortly :) 
https://github.com/Shadows-of-Fire/Apotheosis/commit/1a80720270aeeac098f15ca4b8c0e80e1e723055#diff-40060223ff5e40410b3847ee83495a1d6c46d1a623c2309af2e7e86c5ddb886fR89

**Comment by Kanzaji** [comment]
To be honest, I thought this issue will be related to something with 1.18.2. Didn't expect it to be Apotheosis again 😅
