### ISSUE TITLE
IntegratedDynamics (Mechanical) Squeezer Recipes not showing in JEI

### ISSUE THREAD

**Issue by Moonwolf287** [EnigmaticaModpacks/Enigmatica8#236]
### Modpack Version

2.2.0

### Describe your issue.

JEI does not show the recipes possible with the IntegratedDynamics Squeezer + Mechanical Squeezer. Neither when selecting an ingredient that could be used nor when selecting the squeezer itself to see all the recipes. 
They still work perfectly fine, there is just no information on what recipes are possible.

### Latest Log

https://mclo.gs/bx6ZLCP

### Have you modified the modpack?

Yes

### User Modifications

(I have also checked everything with a clean unmodified version. The log supplied is from the clean version.)

- Remove BYG biomes from Nether
- Changed the cobblestone generator config
- Disabled Alex's Mobs Leafcutter Ants / Anthills
- JEI hid "Cable Facade", "@ Mekanism Creative Gas Tank" & "@ Mekanism Creative Gas Cannister"
- Added the following mods:
  - OpenBlocks Elevator
  - The Mighty Architect

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Moonwolf#6903

**Comment by NielsPilgaard** [comment]
Thanks for the report, looks like having latest ID + JEI fixes this issue, I'll have a look in game :)

**Comment by Moonwolf287** [comment]
As far as I'm aware I have the latest ID (1.11.8) + JEI (9.7.1.255) for 1.18.2?
Aside from updating the two mods is there something else I can do to fix this currently?

**Comment by NielsPilgaard** [comment]
Not that I know of, no :(

**Comment by Moonwolf287** [comment]
Okay so I rechecked and it seems I missed some alpha builds. So either upgrade JEI to 10.X alpha for 1.18.2 or downgrade ID as discussed in ID issue: https://github.com/CyclopsMC/IntegratedDynamics/issues/1204

**Comment by NielsPilgaard** [comment]
Ah yes, now I understand, thanks 😅 I think downgrading is safest, I'll try that now.
