### ISSUE TITLE
[Mod Suggestion]Pam's HarvestCraft 2 Suite

### ISSUE THREAD

**Issue by BamsTheSergal** [EnigmaticaModpacks/Enigmatica8#237]
### URL

https://www.curseforge.com/minecraft/mc-mods/pams-harvestcraft-2-food-core

### Why would you like the mod added?

it would add a lot more variety to farms and new types of trees and such, now that it's for 1.18.2 (all 4 mods), it can finally be used in modpacks of that version. :D

**Comment by NielsPilgaard** [comment]
I'll think about it :)

**Comment by NielsPilgaard** [comment]
I don't think this is a good fit for E8.
