### ISSUE TITLE
Modern UI

### ISSUE THREAD

**Issue by elementsplayer** [EnigmaticaModpacks/Enigmatica8#244]
### URL

https://www.curseforge.com/minecraft/mc-mods/modern-ui

### Why would you like the mod added?

This mod just like the smooth font mod but better! This mod also have some features that can replaces some mods in your modpack so you can run easier. Like Blur, Ding, Inventory Pause and emojiful. 

Although this mod conflict with emojiful, but it built-in a emoji system so you can just replace it without losing emoji system.

**Comment by NielsPilgaard** [comment]
I'm not really interested in what Modern UI offers to be honest 😄
