### ISSUE TITLE
Remove 'Small/Light Modpack' Label

### ISSUE THREAD

**Issue by flameoguy** [EnigmaticaModpacks/Enigmatica8#245]
### Describe your suggestion

The modpack is labeled 'small/light' on curseforge despite having over 270 mods and being fairly taxing on the game's performance. This pack is comparable in size to a large FTB kitchen sink modpack or similar. Enigmatica 8 should be removed from the category since it doesn't fit the description at all.

### Why would you like this added/changed?

It would prevent people with old or low-end computers from wasting their time by downloading a modpack that is too large and hardware intensive to run. It could also help people looking for a more heavily modded experience find and decide to play Enigmatica.

**Comment by NielsPilgaard** [comment]
Good point, I've fixed it just now - Sorry if I've misslead you :)
