### ISSUE TITLE
Comforts mod missing

### ISSUE THREAD

**Issue by TKB9** [EnigmaticaModpacks/Enigmatica8#248]
### URL

https://www.curseforge.com/minecraft/mc-mods/comforts/files/3682307

### Why would you like the mod added?

In your Changlog v 1.0.2 in the new mods section it says that Comforts (Forge) was added.... but it's missing.
Is it possible to re-add it?

**Comment by NielsPilgaard** [comment]
Sure thing

**Comment by TKB9** [comment]
Thank's
