### ISSUE TITLE
[Mod suggestion] assembly line machines

### ISSUE THREAD

**Issue by Mang0z** [EnigmaticaModpacks/Enigmatica8#25]
### URL

https://www.curseforge.com/minecraft/mc-mods/assemblylinemachines

### Why would you like the mod added?

This is a really interesting tech mods that adds pretty viable multiblocks, machines and tools. Also the pack needs some tech so this would fit pretty well i think.
Only issues with the mod are the textures but thats purely asthetic

**Comment by NillerMedDild** [comment]
Approved for the time being, I can't promised it'll remain in the pack in the long run though :)

**Comment by NillerMedDild** [comment]
I've changed my mind, as I have a bad feeling about this mod 😅
