### ISSUE TITLE
Breaking botania floating flower crashes game

### ISSUE THREAD

**Issue by FreekDS** [EnigmaticaModpacks/Enigmatica8#253]
### Modpack Version

2.1.0

### Describe your issue.

Breaking a floating flower from the Botania mod (in survival) crashes the game.
I tested it with a floating endoflame.
Breaking the floating flower in creative does not crash the game.

### Crash Report

https://gist.github.com/FreekDS/cdba193fb1815f8505a94924637345eb

### Latest Log

https://gist.github.com/FreekDS/73a6851d75b04d92010cd27ceba2e92a

### Have you modified the modpack?

Yes

### User Modifications

Added minecolonies (1.18.2-1.0.966-RELEASE)
Added structurize (minecolonies dependency, 1.18.2-1.0.424-ALPHA)
Added domum ornamentum (minecolonies dependency, 1.18.2-1.0.50-ALPHA-universal)
Added multi-piston (minecolonies dependency, 1.18.2-1.0.50-ALPHA-universal)
Added Colony 4 ComputerCraft (1.18.2-2.2.2)

### Did the issue happen in singleplayer or on a server?

Both

**Comment by TemperedFool** [comment]
I'm going to make the educated suggestion that you need to remove all the minecolonies stuff and test again...

**Comment by FreekDS** [comment]
> I'm going to make the educated suggestion that you need to remove all the minecolonies stuff and test again...

I agree, will try this later.

It is worth noting that the flowers were not placed inside the bounds of a colony but I agree we have to eliminate minecolonies causing the troubles.

**Comment by FreekDS** [comment]
Issue remains in unmodified 2.1.0 version of the modpack. 
Seems to be fixed latest 2.2.1 version as Botania has been updated.
The issue is known in the Botania mod (https://github.com/VazkiiMods/Botania/issues/4090).
Closing this issue as it does not occur in latest modpack version.
