### ISSUE TITLE
Changing Akashic Tome to Eccentric Tome

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica8#254]
### Describe your suggestion

I need some opinions on this change, however I think its good idea to change out Akashic Tome to Eccentric Tome.
Eccentric Tome fixes a lot of issues Akashic Tome has, so it's a good QoL change in my opinion.

https://www.curseforge.com/minecraft/mc-mods/eccentric-tome

### Why would you like this added/changed?

It's a fork of Akashic Tome that was intended to fix some bugs for Akashic Tome, but devs of Akashic Tome are ingoring a lot of bug reports, so it was changed to be seperate mod with a lot of stuff fixed :D

**Comment by BooBeerb** [comment]
Me personally, I prefer the Forgotten tome to the mess that is Akashic Tome in 1.18

**Comment by NielsPilgaard** [comment]
I'll have a look, seems promising 👍

**Comment by NielsPilgaard** [comment]
I was hoping the modid hadn't changed, we can't just swap these I'm afraid, too much breakage would ensue.
