### ISSUE TITLE
"Copper Ore" processing output

### ISSUE THREAD

**Issue by Tyrokas** [EnigmaticaModpacks/Enigmatica8#255]
### Modpack Version

2.2.1

### Describe your issue.

- Crushing Wheels 7+1 "Crushed Copper Ore"
- Mechanical Squeezer 8+2+2 "Raw Copper"
- Squeezer 4+2+2 " "
- Smeltery 8 "Molten Copper"
- and so forth

But
- Pulveriser (Thermal) 2 "Copper Dust"
- Crusher (IE) 2 " "
- Mekanism maximization route 5 " "

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Tyrokas#4448

**Comment by NielsPilgaard** [comment]
Myeah it's... a mess 😅

**Comment by Kanzaji** [comment]
Working on it! (Hopefully) I will finish unification work by the end of this week (but no promises 😅 I've started school recently so it's a bit harder to work on on stuff like that)
Also #234 is talking about even more Unification mess ^-^"

**Comment by NielsPilgaard** [comment]
Actually these are all just different processing choices from the mods, nothing seems off in this particular case?

**Comment by Tyrokas** [comment]
oh i thought it was unintentional to have Mechanical Squeezer being occasionally twice as efficent as the full mekanism route
