### ISSUE TITLE
Modpack version 2.2.1 crashes with optifine

### ISSUE THREAD

**Issue by nonging** [EnigmaticaModpacks/Enigmatica8#257]
### Modpack Version

2.2.1

### Describe your issue.

Game crashing during launch when trying to add optifine. Works without it though so it must be incompatibility with optifine. Tried reinstalling and even putting optifine on first launch before adding enigmatica files but crashes when both mod sets are ran together.
Tried getting new files to install like ticket for problem but with version 1.0.4 but still crash.

### Crash Report

https://gist.github.com/nonging/a90fa0b95a992775516d5e9f2ac12fc1

### Have you modified the modpack?

Yes

### User Modifications

Added OptiFine 1.18.2 HD U H7

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by MuteTiefling** [comment]
There's absolutely nothing we can do about optifine, unfortunately. Your best bet is to report directly to them.
