### ISSUE TITLE
Mahogany Boat Missing Texture

### ISSUE THREAD

**Issue by Oofthe3rd** [EnigmaticaModpacks/Enigmatica8#258]
### Modpack Version

2.2.1

### Describe your issue.

When I place the Mahogany boat down, it appears as "Boat" and has the purple and black missing texture all over it.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by NielsPilgaard** [comment]
Thanks for the report 👍 I've relayed it to the appropriate mod's issue tracker.

https://github.com/AOCAWOL/BYG/issues/964
