### ISSUE TITLE
[Suggestion] Gateways to Eternity

### ISSUE THREAD

**Issue by Shadows-of-Fire** [EnigmaticaModpacks/Enigmatica8#260]
### URL

https://www.curseforge.com/minecraft/mc-mods/gateways-to-eterrnity

### Why would you like the mod added?

Just poking this here for reference keeping - I'm pretty sure Niller's aware of it but I don't want it to get buried.

Server-performant data-driven mob farms w/ required player interaction (as opposed to idle mechanics seen in [HNN](https://www.curseforge.com/minecraft/mc-mods/hostile-neural-networks))

**Comment by NielsPilgaard** [comment]
Sure thing, I'm more interested in it for E9 though 😄
