### ISSUE TITLE
Powah and some other ore not generating naturally

### ISSUE THREAD

**Issue by korzinga** [EnigmaticaModpacks/Enigmatica8#264]
### Modpack Version

2.2.1

### Describe your issue.

Either on the developer's side, or just something spaghetti with the modpack, but I've noticed that some ores just refuse to generate, even when loading new chunks in a brand new world. 

### Crash Report

N.a

### Latest Log

N.a

### Have you modified the modpack?

No

### User Modifications

N.a

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Korzinga#7395

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

Which ore others don't generate? :)

**Comment by NielsPilgaard** [comment]
I can't reproduce this I'm afraid.
