### ISSUE TITLE
Botania quests are incorrect

### ISSUE THREAD

**Issue by MCChiter** [EnigmaticaModpacks/Enigmatica8#265]
### Modpack Version

2.2.1

### Describe your issue.

Botania quests require Living WOOD which is a different item that you don't really need. all logs in botania are turned into livingwood LOGS first 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.
