### ISSUE TITLE
Create quests are inaccurate for 1.18

### ISSUE THREAD

**Issue by NickyMB** [EnigmaticaModpacks/Enigmatica8#267]
### Modpack Version

2.2.1

### Describe your issue.

Missing item furnece_engine from create: mode
![image](https://user-images.githubusercontent.com/82083134/190409413-93be9646-f3a5-427e-baf4-e681ba2f8931.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Szef#2794

**Comment by Kanzaji** [comment]
Create quest line is marked as work in Progress! Create god an update where a lot of new things are added :P
