### ISSUE TITLE
[Mod Request] Creative Wireless Transmitter (Refined Storage)

### ISSUE THREAD

**Issue by kamild1996** [EnigmaticaModpacks/Enigmatica8#271]
### URL

https://www.curseforge.com/minecraft/mc-mods/creative-wireless-transmitter

### Why would you like the mod added?

Considering the presence of the AEInfinityBooster mod for Applied Energistics, I believe it's only fair to provide the same feature for Refined Storage users as well.

**Comment by NielsPilgaard** [comment]
Thank you for the suggestion, I'll have a look :)
