### ISSUE TITLE
[Mod Suggestion] Mahou Tsukai

### ISSUE THREAD

**Issue by Grimlock7** [EnigmaticaModpacks/Enigmatica8#272]
### URL

https://www.curseforge.com/minecraft/mc-mods/mahou-tsukai

### Why would you like the mod added?

I think its a very unique magic mod that would be enjoyable to mess around with! Plus nearly everything is configurable in the mod from mana costs, to mana regen, to SFX volume, to rendering, to spell sizes/effects, to how often certain spells tick.

**Comment by NielsPilgaard** [comment]
I dislike it tbh, no thanks :)
