### ISSUE TITLE
[Missing mod/s] Some of FTB Utilities mods are missing!

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica8#273]
### Modpack Version

2.1.0 and above

### Describe your issue.

in the issue #40, a few FTB utilites mods were added (like FTB essentials) but few of them are just missing :P

FTB Utilites is missing since 2.1.0 (or even 2.0)
FTB Ranks is missing since (I... have no idea ^^")

Tbh I'm shocked that no one didn't suggest FTB Utilities being added for so long 😅 

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Kanzaji#0621

**Comment by NielsPilgaard** [comment]
> FTB Utilites is missing since 2.1.0 (or even 2.0)

That mod doesn't exist for 1.16.5+ iirc

I decided to leave out FTB Ranks, I believe it can be used serverside only if server owners want it anyway. (Don't quote me on that I'm not 100% sure 😄)

**Comment by Kanzaji** [comment]
BIG WOOPS, I wrote the wrong name of the mod! I'm sorry Niller 😓 
I was talking about FTB Essentials https://www.curseforge.com/minecraft/mc-mods/ftb-essentials-forge
Should I open new issue or edit this one and we could maybe re-open ^-^"?

**Comment by NielsPilgaard** [comment]
No FTB Essentials either, I'll leave that up to server owners 👍

**Comment by Kanzaji** [comment]
Awww, alrighty then 👍
