### ISSUE TITLE
CurseForge Distrubition has missing files / configs!

### ISSUE THREAD

**Issue by Kanzaji** [EnigmaticaModpacks/Enigmatica8#274]
### Modpack Version

2.1.0 and above (Tested out 2.1.0, 2.2.1, 2.3.0)

### Describe your issue.

CurseForge downloads doesn't have custom Enigmatica 8 Main menu! Github distribution doesn't have this problem:
Github:
![obraz](https://user-images.githubusercontent.com/60540476/190817335-650119ec-a435-41f7-8d11-5781edc3621f.png)

CF 2.1.0, 2.2,1 and 2.3.0 Downloads:
![obraz](https://user-images.githubusercontent.com/60540476/190819401-3c492c02-c2a0-4d24-a649-5669b38404ba.png)

Note: Each of CF distributions was installed with use of PolyMC*

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Kanzaji#0621

**Comment by Kanzaji** [comment]
#275 -> Same type of issue, CurseForge .zip has missing files

**Comment by NielsPilgaard** [comment]
Hmm, the packmenu folder is included in the zip, I'll investigate what's going on here.

**Comment by NielsPilgaard** [comment]
No clue so far, easy to reproduce with a new CF download though at least
