### ISSUE TITLE
Guide book broken in new worlds

### ISSUE THREAD

**Issue by luna6667** [EnigmaticaModpacks/Enigmatica8#275]
### Modpack Version

Enigmatica8-2.3.0 

### Describe your issue.

Installed the pack today (Fresh install, not update), Grabbed the "Modding for Dummies" book in a fresh world but it was invalid. Happened in 2 worlds. I did search for this but couldn't find if it had been reported. 
![image](https://user-images.githubusercontent.com/11493210/190839842-2d4860d5-4503-4742-9241-918ef7ce5e76.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Luna6667#1656

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by Kanzaji** [comment]
@NielsPilgaard Found an issue! Book isn't just delivered with CF distributions 😅

**Comment by NielsPilgaard** [comment]
Woops, fixed 😄
