### ISSUE TITLE
Immersive Engineering's Blast Furnace output of Slag broken ("Empty Tag: forge:slag")

### ISSUE THREAD

**Issue by kamild1996** [EnigmaticaModpacks/Enigmatica8#278]
### Modpack Version

2.3.0

### Describe your issue.

Improved Blast Furnace (and most likely the base variant) outputs barrier items with the name "Empty Tag: forge:slag". Regression compared to E8 2.2.1.
![image](https://user-images.githubusercontent.com/5320414/190913902-8508fbab-4cef-48ba-8516-6e23050ffcf1.png)

### Crash Report

n/a

### Latest Log

n/a

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

kamild_#2840

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by NielsPilgaard** [comment]
Reported here: https://github.com/AlmostReliable/almostunified/issues/5

**Comment by NielsPilgaard** [comment]
Fixed in dev, it was our own scripts messing it up 😄

**Comment by mjevans** [comment]
You might also want to add something similar to this to fix barrier blocks generated as slag.

```js
onEvent('recipes', event => {
  event.shapeless('thermal:slag', '#forge:slag').id('e8:fix230slag')
  event.shapeless('thermal:slag', 'minecraft:barrier').id('e8:fix230slag')
})
```

**Comment by glodomorrapl** [comment]
Thank you for the fix! Before I make another report, does the referenced commit also fix slag from either mod getting smelted into white rockwool?

**Comment by kamild1996** [comment]
Does the referenced commit also fix slag being smelted into white rockwool?

**Comment by NielsPilgaard** [comment]
> You might also want to add something similar to this to fix barrier blocks generated as slag.
> 
> ```js
> onEvent('recipes', event => {
>   event.shapeless('thermal:slag', '#forge:slag').id('e8:fix230slag')
>   event.shapeless('thermal:slag', 'minecraft:barrier').id('e8:fix230slag')
> })
> ```

Good call 👍 

> Does the referenced commit also fix slag being smelted into white rockwool?

It does not, it should be Light Grey Rockwool right?

**Comment by kamild1996** [comment]
> > Does the referenced commit also fix slag being smelted into white rockwool?
> 
> It does not, it should be Light Grey Rockwool right? Edit: I just checked the Thermal datapack, and it is now meant to be white.
The Thermal Series slag, yes. But there's also the Immersive Engineering slag, which is supposed to smelt into Slag Glass. https://github.com/BluSunrize/ImmersiveEngineering/issues/5316
Maybe these two slags shouldn't be unified after all?
