### ISSUE TITLE
Gregtech Intergalactical

### ISSUE THREAD

**Issue by Leclowndu93150** [EnigmaticaModpacks/Enigmatica8#279]
### URL

https://www.curseforge.com/minecraft/mc-mods/gregtech-intergalactical

### Why would you like the mod added?

Gr🥚

**Comment by Kanzaji** [comment]
Duplicate of #277.

**Comment by Leclowndu93150** [comment]
> Duplicate of #277.

i know

**Comment by Gcat101** [comment]
NO STOP DON'T SPAM THIS WAS JUST A LITTLE TROLLING DO NOT SPAM OK
