### ISSUE TITLE
Book of Natural Aura - Emptyh

### ISSUE THREAD

**Issue by Alnarra** [EnigmaticaModpacks/Enigmatica8#280]
### Modpack Version

2.3.0

### Describe your issue.

The Natural Aura book appears to have Zero Categories or information. There appears to be an error present 
 
![image](https://user-images.githubusercontent.com/15974903/191064934-fe482af1-339c-4f18-8950-03cd505b3624.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

### Discord Username

Alnarra#3724

**Comment by Kanzaji** [comment]
Thanks for the report! We will investigate the issue.

(Also a bit of research reveals that similar bug was occurring for other's, I think I know what could go wrong 😅)
https://github.com/Ellpeck/NaturesAura/issues/256

**Comment by Kanzaji** [comment]
https://github.com/AlmostReliable/almostunified/issues/4 -> I'm fairly sure its Jaopca and / or Almost Unified causing the issue. Seems like it is just "wait for fix" type of issue.

**Comment by NielsPilgaard** [comment]
I think you're right 👍

**Comment by NielsPilgaard** [comment]
That didn't fix it sadly, not sure what's going on 🤔

**Comment by Kanzaji** [comment]
Let's hope fix will work and resolve this 😄

**Comment by Kanzaji** [comment]
Update on the issue: Me and one of the devs of AU were testing out the new patch for this, and they decided to use Orginal ID of the recipe :D
I think fix should be already out, anyhow it works perfectly and all books we have in E8 are working with new version of AU.

**Comment by NielsPilgaard** [comment]
Sweeet!

**Comment by GnomTocha** [comment]
![2022-09-26_10 42 20](https://user-images.githubusercontent.com/75666317/192221287-6661f004-e43d-44e1-b6f5-24064aa637d3.png)

I would like to add that such a problem occurs with the book The Twilight Forest .
Side: Server/client

**Comment by NielsPilgaard** [comment]
Fixed in 2.3.1 :)

**Comment by Kanzaji** [comment]
It is not fixed in 2.3.1 😅 Twilight forest book is just... broken all together.
Was talking with devs of TF, they aren't going to fix this, as this book was removed in 1.19 version :c Probably we should hide the book from JEI and remove from quest Akashic / Eccentric tome.

**Comment by NielsPilgaard** [comment]
Oh 😅

**Comment by GnomTocha** [comment]
> 

Just noticed the alpha. Waiting for beta or release. I'll update then.

**Comment by NielsPilgaard** [comment]
Updated to beta just now :)

**Comment by GnomTocha** [comment]
Damn fast 😆
