### ISSUE TITLE
[Suggestion] Mana & Artifice

### ISSUE THREAD

**Issue by V2LenKagamine** [EnigmaticaModpacks/Enigmatica8#285]
### URL

https://www.curseforge.com/minecraft/mc-mods/mana-and-artifice

### Why would you like the mod added?

This mod is amazing. I have no words for it that could describe its balance and beauty. It is well made, and has little performance impact for the sheer amount of content the mod contains.

**Comment by NielsPilgaard** [comment]
After having a look in-game I've settled on a no sadly.
