### ISSUE TITLE
Certus Quartz Duplication Bug

### ISSUE THREAD

**Issue by Owningle** [EnigmaticaModpacks/Enigmatica8#288]
### Modpack Version

2.3.0

### Describe your issue.

Certus quartz block only takes 4 certus quartz to craft, but when put in a smeltery will produce 900mb of molten certus quartz, which can then be used to create 9 certus quartz, as they require 100mb each.

### Have you modified the modpack?

Yes

### User Modifications

https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance
https://www.curseforge.com/minecraft/mc-mods/entity-collision-fps-fix
https://www.curseforge.com/minecraft/mc-mods/fastload
https://www.curseforge.com/minecraft/mc-mods/radium-reforged
https://www.curseforge.com/minecraft/mc-mods/rubidium
https://www.curseforge.com/minecraft/mc-mods/starlight-forge

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Owningle#9643

**Comment by Kanzaji** [comment]
Feels like another unification bug 😅? However with certus, there is already an infinite certus loop with default AE2 so this is not a game breaker ^^"
Anyhow thanks for the report! We will investigate the issue :D
