### ISSUE TITLE
Blaze rod duplication

### ISSUE THREAD

**Issue by Owningle** [EnigmaticaModpacks/Enigmatica8#289]
### Modpack Version

2.3.0

### Describe your issue.

A blaze rod requires 4 blaze powder to craft using a metal press.
![image](https://user-images.githubusercontent.com/34453764/192765662-7b7f8087-b677-49a1-a7fd-cd84b307e172.png)

A blaze rod can be turned into 5 blaze powder in the following methods:
![image](https://user-images.githubusercontent.com/34453764/192765757-edd4c861-0b20-4f0e-af72-10df6bfdd153.png)

![image](https://user-images.githubusercontent.com/34453764/192765808-04d19f00-61f7-4879-b809-f192f3217ed0.png)

Can also use this to create infinite sulfur:
![image](https://user-images.githubusercontent.com/34453764/192765964-bd894310-66e4-4014-9d14-1a5ef9440ba7.png)

### Have you modified the modpack?

Yes

### User Modifications

https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance
https://www.curseforge.com/minecraft/mc-mods/entity-collision-fps-fix
https://www.curseforge.com/minecraft/mc-mods/fastload
https://www.curseforge.com/minecraft/mc-mods/radium-reforged
https://www.curseforge.com/minecraft/mc-mods/rubidium
https://www.curseforge.com/minecraft/mc-mods/starlight-forge

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Owningle#9643

**Comment by Kanzaji** [comment]
Thanks for the report! This is fairly simple fix ^^
