### ISSUE TITLE
Nether wart duplication

### ISSUE THREAD

**Issue by Owningle** [EnigmaticaModpacks/Enigmatica8#290]
### Modpack Version

2.3.0

### Describe your issue.

Nether wart block created using 4 nether wart.
![image](https://user-images.githubusercontent.com/34453764/192767124-cfb4514e-36c1-4c91-8965-dfbccd582dd4.png)

Nether wart block can be used to make 9 netherwart
![image](https://user-images.githubusercontent.com/34453764/192767247-94d8f38e-7667-4bb9-912b-cef020c18100.png)

### Have you modified the modpack?

Yes

### User Modifications

https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance
https://www.curseforge.com/minecraft/mc-mods/entity-collision-fps-fix
https://www.curseforge.com/minecraft/mc-mods/fastload
https://www.curseforge.com/minecraft/mc-mods/radium-reforged
https://www.curseforge.com/minecraft/mc-mods/rubidium
https://www.curseforge.com/minecraft/mc-mods/starlight-forge

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

Owningle#9643

**Comment by Kanzaji** [comment]
Woops, something ain't right here 😓 
![obraz](https://user-images.githubusercontent.com/60540476/193030846-c89691ec-81f9-48ed-a89c-c208bb6f3806.png)
