### ISSUE TITLE
[bug] Quest Book - Occultism - Janitor / Cleaner won't unlock

### ISSUE THREAD

**Issue by mjevans** [EnigmaticaModpacks/Enigmatica8#295]
### Modpack Version

2.3.0

### Describe your issue.

I have completed all of the quests in Occultism except for one; the single quest tied to an advancement.  1.18.2 seems to have different advancements than 1.16 (E6).

```/say @a[advancements={minecraft:story/mine_diamond=true}]```

I see [playername] playername when I run the above command.

```/say @a[advancements={occultism:summon_foliot_cleaner=true}]```

Doesn't exist, I have completed the ritual, I've got a book that holds the janitor, and I've even tried having them clean up items into my dump-chest.

```/say @a[advancements={occultism:occultism/summon_foliot_cleaner=true}]```

With the double prefix the test succeeds.

PS: there's also a typo "				title: "Summon Foliiot Janitor"  

Edit: copy/paste didn't include the =true part.

https://github.com/EnigmaticaModpacks/Enigmatica8/blob/14dfa044c39e46a654bbd85419b2e20823c585ed/config/ftbquests/quests/chapters/occultism.snbt

### Have you modified the modpack?

Yes

### User Modifications

N/A to this issue.

### Did the issue happen in singleplayer or on a server?

Server

**Comment by Kanzaji** [comment]
Problem with occultism quests were, that Occultism doesn't have advancements at all on 1.18.2 😅 It is possible tho that I've missed one of the quests with the "rework" tho, so gonna see what is wrong there, Thanks for the report!
