### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by shadowslayer2233** [EnigmaticaModpacks/Enigmatica8#297]
### Modpack Version

1.18

### Describe your issue.

it says missing dependency 3950762 if i try to download

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

shadow_senpai#9683

**Comment by DAmNRelentless** [comment]
That seems to be a very common issue right now. People on ATM packs have the same problem.
It's Apotheosis triggering that.

**Comment by NielsPilgaard** [comment]
Which modpack version are you on? It's displayed near the pack name in the CurseForge app.

**Comment by DAmNRelentless** [comment]
Several people said this is fixed now. Seemed to be a little hiccup in the CurseForge backend.

**Comment by NielsPilgaard** [comment]
Awesome, thanks!
