### ISSUE TITLE
Camera Mod

### ISSUE THREAD

**Issue by MrFHering** [EnigmaticaModpacks/Enigmatica8#298]
### URL

https://www.curseforge.com/minecraft/mc-mods/camera-mod

### Why would you like the mod added?

Just wanted to chuck this mod in for consideration. It could be easily seen as bloat but it adds some really nice features for decoration. Particularly being able to import images makes for some really fun decoration possibilities.

**Comment by NielsPilgaard** [comment]
Cool mod, but I kinda see it as bloat tbf.
