### ISSUE TITLE
Skyblock 

### ISSUE THREAD

**Issue by NickyMB** [EnigmaticaModpacks/Enigmatica8#301]
### Describe your suggestion

My suggestion is to make Skyblock Version of modpack

### Why would you like this added/changed?

Last Enigmatica Skyblock was on 1.12. I wish there were new Skyblock on newer mods

**Comment by NielsPilgaard** [comment]
I'm afraid we don't have the time to make a skyblock version of the modpack at the moment. Perhaps for another pack down the line.
