### ISSUE TITLE
FTB Ultimine / Integrated Dynamics and Malum compatibility

### ISSUE THREAD

**Issue by HalJordan** [EnigmaticaModpacks/Enigmatica8#303]
### Modpack Version

2.3.2

### Describe your issue.

This was actually fixed(or at least there were a few issues opened on it and a patch provided) but it's been broken. The kubejs script that sets up the combined item tag switched to using integrateddynamics:menril_logs instead of ftbultimine:menril_logs.

Malum has a similar tag needed so that you can fell their whole trees, malum:runewood_logs. Adding these to merge_tags in ftbultimine-server.snbt fixes both.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
Thanks for the report, and even providing the fix :D

**Comment by HalJordan** [comment]
It's getting very frustrating that I'm having to do it for every pack. It seems(and I can't say I really disagree here tbh) that between the modpack, Ultimine, and whatever other mod is concerned, all 3 are pointing the finger elsewhere.

Ideally, it shouldn't be a problem for any mod author to setup such a group, then it's a simple matter of ultimine to add that to the default list. It's quite annoying that they're just balking on something so simple.

**Comment by MuteTiefling** [comment]
While I understand the frustration, this is probably not the right place to vent it.

We generally have no issue adding such helper tags, but if the mod authors aren't willing to do it themselves, all we can do is fix it in our pack.
