### ISSUE TITLE
Immersive Engineering issue with Uranium blocks

### ISSUE THREAD

**Issue by gfear** [EnigmaticaModpacks/Enigmatica8#309]
### Modpack Version

2.3.2

### Describe your issue.

Is the uranium broken for immersive engineering thermoelectric generators? I cannot get the grey uranium block anymore. and the green one does not seem to work for me. This is on Enig 8 v2.3.2. I just looked on single player and the immersive engineering block is there but not on the server. but the green on still doesn't work on the singleplayer

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

GFear

**Comment by NielsPilgaard** [comment]
Thanks for the report. I guess the unification mod has been a bit too thorough here :D

**Comment by gfear** [comment]
All good. :) Yall have been doing great on the mod pack.

**Comment by DAmNRelentless** [comment]
In the newest version, we introduced a new option for Almost Unified for priority overrides, which lets you define a specific mod per tag. So you can use something like `"forge:storage_blocks/uranium": "immersiveengineering"` which would solve this.

**However**, after a bit of investigation, the Immersive Engineering Thermoelectric Generator is JSON recipe based and takes an uranium storage block tag as it should: https://github.com/BluSunrize/ImmersiveEngineering/blob/1.18.2/src/generated/resources/data/immersiveengineering/recipes/thermoelectric/uranium.json

And I also tested it in a local world and the result was that the Mekanism Uranium block does count for energy generation.

https://user-images.githubusercontent.com/16513358/196739627-6deaa248-1f19-47b0-83b0-a368eaf434e4.mp4

So if it does not work in E8, the tag for the priority uranium block is missing.
Either way, this can be solved now.
