### ISSUE TITLE
Lost pages in the book of mod occultism.

### ISSUE THREAD

**Issue by GnomTocha** [EnigmaticaModpacks/Enigmatica8#312]
### Modpack Version

2.3.2

### Describe your issue.

Recently upgraded client side and server side from version 2.3.0 to 2.3.2. Akashic Tome does not display much of the information from the occult mod. Some are completely missing.
![2022-10-18_12 22 44](https://user-images.githubusercontent.com/75666317/196394686-a31abc19-799c-459f-b1cd-590de512c812.png)
![2022-10-18_12 22 49](https://user-images.githubusercontent.com/75666317/196394696-09044dc6-28d3-451a-880d-24b0e13649c3.png)
![2022-10-18_12 22 54](https://user-images.githubusercontent.com/75666317/196394698-7a3ded08-f4ec-49e3-9497-37fbdcdc3b1b.png)
![2022-10-18_12 23 18](https://user-images.githubusercontent.com/75666317/196394700-5955164f-94d3-4b3a-8e20-a83ac4202b8f.png)
![2022-10-18_12 23 24](https://user-images.githubusercontent.com/75666317/196394702-c8aa442d-5e26-4aba-84e1-065777ba9dee.png)

### Latest Log

<script src="https://gist.github.com/GnomTocha/96813ad3715cd9c699850d31e5f424b5.js"></script>

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

### Discord Username

KonTa#1746

**Comment by MuteTiefling** [comment]
They released it so they could get feedback as they work on it.

**Comment by GnomTocha** [comment]
Now I noticed that there is a recipe for getting an old book. It would be nice to add it in future updates as a second book to choose from in Akashic Tome.
