### ISSUE TITLE
[Tinker's Construct] Most of tool's textures are missing

### ISSUE THREAD

**Issue by MitsuiKigetsu** [EnigmaticaModpacks/Enigmatica8#313]
### Modpack Version

2.3.2

### Describe your issue.

All of the tool's texture are missing.
It happens with the item itself once being created, some parts and the preview item on the left in the "Tinker Station".

Some part like cobblestone one are fine but the final full cobblestone tool's texture are also missing
Done the test with the basic material.
- Wood (Birch tool parts have no texture)
- Cobblestone
- Flint

In the JEI, we can see what part has a missing texture and we can also see that every tool have no texture.

Done some testing with the mod concerned and Forge only and texture were present.
Same version as the mod in the modpack.

### Crash Report

No Crash Report

### Latest Log

https://gist.github.com/MitsuiKigetsu/95bcee1e946869f6a1f9d8b17569db6b

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

THEdarkkman#4359

**Comment by Kanzaji** [comment]
Thank you for the report, we will investigate the issue :D

**Comment by MitsuiKigetsu** [comment]
Did some restart, texture still missing. After a /reload (not sure because also restart right after) the texture are present now.
The only difference between before and now is some config tweak (ftbultimine serverconfig set to 256).

Decided to restart again to see if this now "fixed" and no more issue. Not sure what happen but will happily provide any information to you guys if needed :D

**Comment by NielsPilgaard** [comment]
Hmm, did you use F3+T at some point before you noticed the bug?

**Comment by NielsPilgaard** [comment]
I hope that's the case, cause that has a tendency to mess up... many things 😄
