### ISSUE TITLE
Remove duplicate ore blocks from different mods

### ISSUE THREAD

**Issue by pPkMnh4to8994h** [EnigmaticaModpacks/Enigmatica8#318]
### Describe your suggestion

As of now, ores like Nickel and Aluminium/Bauxite are generating from different mods simultaneously. For example, Aluminium from FTB Industrial Contraptions and Bauxite from Immersive Engineering. While this is not a major problem by itself, packs usually tend to have only one type of ore present in world.

### Why would you like this added/changed?

Have only one type of ore present in worlds for consistency purposes.

**Comment by NielsPilgaard** [comment]
Woops, I thought I got rid of all the duplicates 😅 thanks for the report, I'll get that fixed.

**Comment by NielsPilgaard** [comment]
So IE Bauxite is actually disabled, it should not generate. Which Nickel types have you seen? If it's IE as well, I'd wager something went wrong with the IE server config of your instance.

**Comment by pPkMnh4to8994h** [comment]
All right, I went to check in singleplayer and it is indeed disabled...
I guess something on my server went wrong.
