### ISSUE TITLE
Hard Crash on Advancements Open

### ISSUE THREAD

**Issue by Tony2Scoops** [EnigmaticaModpacks/Enigmatica8#321]
### Modpack Version

2.3.2

### Describe your issue.

There is a hard crash when opening the advancements screen.  FTBquests is fine, but when you open the better advancements screen it crashes to desktop.

### Crash Report

https://gist.github.com/Tony2Scoops/a7d798ee836570bd79f0c9cd7bc7d60e

### Latest Log

https://gist.github.com/Tony2Scoops/54bf15b301b5e710eb2f210990845477

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by Tony2Scoops** [comment]
I actually realized I did add a mod to the pack.  I added JER and Easy Villagers.  I will remove those and test to see if I have the same issue.
