### ISSUE TITLE
Uncrafting Table in Twilight Forest chest

### ISSUE THREAD

**Issue by 0sdrawkcaB** [EnigmaticaModpacks/Enigmatica8#322]
### Modpack Version

2.3.2

### Describe your issue.

I found an Uncrafting Table in a loot chest within the twilight forest dimension, under twilight highlands.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.
