### ISSUE TITLE
I made a new world and broke a palm log, then

### ISSUE THREAD

**Issue by GabSolo** [EnigmaticaModpacks/Enigmatica8#324]
### Modpack Version

2.3.2

### Describe your issue.

then I got the "Why are you cheating bro?" Achievement (Transmit a network signal with a creative wireless transmitter accross dimensions at infinite range)
I just broke a palm log

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Lord of Gab#6591

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by MindBrain27** [comment]
I too had the same thing with clay.

**Comment by Kanzaji** [comment]
Relayed it here: https://github.com/starforcraft/Creative-Wireless-Transmitter/issues/4

**Comment by Kanzaji** [comment]
The issue appears that it was fixed ^^" We just need to update the mod.
