### ISSUE TITLE
No Night Vision Flashing lighting bug while using any shaderpack

### ISSUE THREAD

**Issue by richiehailstone** [EnigmaticaModpacks/Enigmatica8#326]
### Modpack Version

Enigmatica8-2.3.2

### Describe your issue.

**The bug**: At night and in dark caves, the lighting acts as if you had permanent night vision on.
Everything is very bright, regardless of video settings.

**The quick fix**: (No relog necessary): Pause -> Mod options -> "No Night Vision Flashing" -> set "Max Brightness" from 1.0 to 0.0
_However, I tested this further, and sadly this quick fix causes the actual night vision potion effect to stop functioning._

**The true fix**: Fully disable the "no_nv_flash-1.18.2-1.4.0.2" mod.
This will fix the lighting bug while also allowing night vision potion effects to work.

The flashing never really bothered me anyway... Maybe the easiest solution going forward for everyone is to just temporarily disable the mod in the next update? 
I will also report this issue to the CoFH team so they can see if anything can be done on their end.

For photos of bug and fix: 
https://www.reddit.com/r/Enigmatica/comments/z29s67/enigmatica_8_shaders_no_dark_lighting_fix/

### Have you modified the modpack?

Yes

### User Modifications

Rubidium + Oculus + Various shader packs

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

hailstone#0001

**Comment by MuteTiefling** [comment]
Thanks for sharing, but this isn't a pack issue. We don't ship shaders.
