### ISSUE TITLE
Mazestone spawns in random stone generators

### ISSUE THREAD

**Issue by Golfavel** [EnigmaticaModpacks/Enigmatica8#328]
### Modpack Version

2.3.2

### Describe your issue.

Mazestone can generate in random stone generators, which can practically halt mineral acquiring.
![mazestonegen](https://user-images.githubusercontent.com/32048635/205477779-9741bd96-4155-464f-97e5-d709292219cd.png)

### Have you modified the modpack?

Yes

### User Modifications

```
Clumps
CraftingTweaks
Rubidium
Entity Collision FPS Fix
Entity Culling
Out of Sight
```

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Woops 😅 thanks for letting us know!
