### ISSUE TITLE
[Mod Suggestion] Extreme Reactors

### ISSUE THREAD

**Issue by 0xicl33n** [EnigmaticaModpacks/Enigmatica8#33]
### URL

https://www.curseforge.com/minecraft/mc-mods/extreme-reactors

### Why would you like the mod added?

Powerful and modular power generation, works with CC. Does not explode like mek reactors and building turbine/radiators doesn't require a degree in engineering. Reactors can be switched to use uranium(from mek or wherever) instead of yellorium

**Comment by 0xicl33n** [comment]
ER only supports 1.18.1. Not 1.18.

**Comment by tuca1234567890** [comment]
dev is already at 1.18.1 though, i don't think you should close this yet

**Comment by 0xicl33n** [comment]
I was not aware of that. I will leave it open
