### ISSUE TITLE
Inlay cast

### ISSUE THREAD

**Issue by Raven0803** [EnigmaticaModpacks/Enigmatica8#330]
### Modpack Version

2.4.1

### Describe your issue.

In the Tinker's quest line you have to make an Inlay cast. But it don't show the recipe for it. And it also don't show up up when you seach for Materialis in JEI

![image](https://user-images.githubusercontent.com/120822196/208256458-6896ceb4-8203-4f49-a940-98692dba65b6.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

raven

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.
