### ISSUE TITLE
Add the antimatter recipe for artifact infinity tools

### ISSUE THREAD

**Issue by Andstar** [EnigmaticaModpacks/Enigmatica8#331]
### Describe your suggestion

Add the old Antiprotonic Nucleosynthesizer recipe for artifact tier infinity tools from enigmatica 6 to engimatica 8

### Why would you like this added/changed?

It looks like the antimatter recipe from the nucleosynthesizer to upgrade the industrial foregoing infinity tools got removed and no alternative was added so the challenge quest is virtually impossible in survival without an insane grind and waiting time

**Comment by NielsPilgaard** [comment]
Good idea 👍
