### ISSUE TITLE
Missing Quest items

### ISSUE THREAD

**Issue by ValeK-tpa** [EnigmaticaModpacks/Enigmatica8#334]
### Modpack Version

2.4.1

### Describe your issue.

Many missing quest items/triggers, especially on the Ars quest page.
![image](https://user-images.githubusercontent.com/7911647/210344660-921837f8-2cc5-43e3-a66c-3a00f88d02e5.png)

### Have you modified the modpack?

Yes

### User Modifications

Changed the Range of the Mega torch and increased filter slots in Sophisticated backpacks

### Did the issue happen in singleplayer or on a server?

Both

**Comment by Kanzaji** [comment]
Thanks for the report. Take a note those are marked as Work In Progress tho :wink:

**Comment by Kanzaji** [comment]
@NielsPilgaard this issue, and #330 #267 #265 have been all fixed in #335 😅
