### ISSUE TITLE
Add JAMD mining dimension

### ISSUE THREAD

**Issue by policeMarcus** [EnigmaticaModpacks/Enigmatica8#336]
### URL

https://www.curseforge.com/minecraft/mc-mods/jamd

### Why would you like the mod added?

This modpack is in deep need of a mining dimension, especially with Create installed which tempts me to make chunk miners (inchworm miners). It would be generally easier to get the resources you need.
I only see pros with adding this, a nice light-weight addition.

**Comment by NielsPilgaard** [comment]
.. Sure why not 😄

**Comment by policeMarcus** [comment]
Thanks! :)

**Comment by NielsPilgaard** [comment]
We usually leave issues open until they've been released :)

**Comment by policeMarcus** [comment]
Oh sorry. Do you have any idea about when the next update for the modpack is coming? I suppose when you get quite the pile you publish everything in one sweep?
