### ISSUE TITLE
Disable cheery (mob?) jukebox music

### ISSUE THREAD

**Issue by Lartza** [EnigmaticaModpacks/Enigmatica8#338]
### Describe your suggestion

What I've gathered to be a mob event, is a random cheery music that starts playing randomly on global jukebox channel with no direction.

### Why would you like this added/changed?

Besides the issues where it cuts off randomly, and can repeat multiple times in under half a minute like it just did for me, it's almost obnoxiously loud and feels always out of place when you can't even hunt it's source.

Even if you could if it were underground etc it would be annoying to do so.

**Comment by FooterMan14** [comment]
That is caused by Sophisticated Backpacks spawning an entity with a backpack containing a Jukebox upgrade. It cuts off randomly because mobs wearing a backpack move quicker :)

**Comment by Kanzaji** [comment]
I am fairly sure it is possible to disable it tho, gonna investigate it a bit 😄

**Comment by NielsPilgaard** [comment]
It's enabled on purpose, I quite like it 😄

**Comment by Kanzaji** [comment]
So a bit late response: Yea it is possible to disable it, but it should also be possible to tune them down by Jubekox slider in the sound menu 😄
(And after a talk in Contributor chat, I pretty much knew the answer 😆)
