### ISSUE TITLE
Hemp Seeds from Immersive Engineering don't drop from grass

### ISSUE THREAD

**Issue by Lartza** [EnigmaticaModpacks/Enigmatica8#339]
### Describe your suggestion

Make a new quest or add industrial hemp seeds as a reward to an existing quest.

### Why would you like this added/changed?

![javaw_WEpLRwhckw](https://user-images.githubusercontent.com/305616/214411340-a6e165b9-13d6-4d43-a5db-c76d3c9cd5d2.png)

**Comment by Lartza** [comment]
Could fit better as a bug report to fix or workaround in another way too but I'm not here to figure that out necessarily :P

**Comment by Kanzaji** [comment]
@NielsPilgaard Can you change the name of this to "Hemp Seeds from Immersive Engineering don't drop from grass" Or something similar 😄? Just got a fix for that weird issue with them not droping at all.
