### ISSUE TITLE
End Pyramids explode upon loading, destroying all loot

### ISSUE THREAD

**Issue by Lartza** [EnigmaticaModpacks/Enigmatica8#341]
### Modpack Version

2.4.1

### Describe your issue.

End Pyramids explode almost instantly upon generation.

Despite this claiming it has been fixed, it seems to not be https://github.com/TelepathicGrunt/RepurposedStructures/issues/215

### Have you modified the modpack?

Yes

### User Modifications

Server modified with:
Radium
Radon
Removed FTB Backups

Reproduced singleplayer modified with:
Rubidium
Rubidium Extra
TexTrue's Rubidium Options
Oculus
Iris & Oculus Flywheel Compat
Entity Collision FPS Fix

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NielsPilgaard** [comment]
Thanks for the report - I needed to modify the lootr config a bit it seems.
