### ISSUE TITLE
RS Infinity Booster

### ISSUE THREAD

**Issue by phoenixborn635** [EnigmaticaModpacks/Enigmatica8#343]
### URL

https://www.curseforge.com/minecraft/mc-mods/rsinfinitybooster

### Why would you like the mod added?

There's one for AE2 but not refined storage

**Comment by Rhyssia** [comment]
Just wanted to point out that " RSInfinityBooster " would add redundancy to " creativewirelesstransmitter-1.18.2-1.2.jar " which is included in the mods as of 2.4.1

Link to Creative Wireless Transmitter:
https://www.curseforge.com/minecraft/mc-mods/creative-wireless-transmitter

**Comment by NielsPilgaard** [comment]
Thats what it's called! I had s feeling I already added this once 😂 ty!
