### ISSUE TITLE
Entities and particles are invisible 

### ISSUE THREAD

**Issue by BlueHero233** [EnigmaticaModpacks/Enigmatica8#345]
### Modpack Version

2.4.1

### Describe your issue.

When loading in a world, entities and particles like the bonus chest, mobs, the player hand model, dropped items and breaking particles are invisible. Upon a google search, apparently its a compatibility issue with Alex Mobs and Configured

https://www.reddit.com/r/feedthebeast/comments/w79efx/all_entities_are_invisible_upon_loading_the_world/

Its not unplayable right now but i think it deserves a little attention

### Latest Log

https://gist.github.com/BlueHero233/5206179e0da06a3597cd37676eabf292

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Kanzaji** [comment]
Did you open the mod config menu in game before joining a world 😅?

**Comment by BlueHero233** [comment]
As a matter of fact i did, didnt touch in any of the configs though, only momentarily glanced at the modlist

Just now: if i close the instance and open it again, load the world without touching the mod config menu, the said entities now render... peculiar

**Comment by Kanzaji** [comment]
Yea that is a known bug, just don't touch the mod config menu as for now 😅

**Comment by NielsPilgaard** [comment]
Link to the issue: https://github.com/AlexModGuy/AlexsMobs/issues/1547
