### ISSUE TITLE
Tinkers Repair Kit Quest Reward Broken

### ISSUE THREAD

**Issue by Crazyafk** [EnigmaticaModpacks/Enigmatica8#346]
### Modpack Version

2.4.1

### Describe your issue.

I got a common tinkers quest reward, which gave me 5 tinkers repair kits.
The issue is that these kits are missing a material, making them completely useless as they cannot be used to repair anything.
Thanks

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.
