### ISSUE TITLE
Updating Flywheel to fix a crash on AMD GPUs

### ISSUE THREAD

**Issue by Prastal** [EnigmaticaModpacks/Enigmatica8#350]
### Describe your suggestion

Flywheel has gotten a hotfix to stop [crashes on AMD GPUs](https://github.com/Jozufozu/Flywheel/issues/164) after an update made the game unplayable on AMD GPUs. Current version of enigmatica 8 crashes if you have a chest unless you either turn the flywheel backend off or update to the new hotfix.

### Why would you like this added/changed?

Fixes a crash that affects a moderate chunk of the playerbase. And considering the error code you get from a crash is very vague (you just get an exit code on Prism Launcher) it should be adressed ASAP.

**Comment by NielsPilgaard** [comment]
Man that's a relief 😅 I'll get this fixed asap, ty.
