### ISSUE TITLE
JAMD Mining dimension not generating ores

### ISSUE THREAD

**Issue by AlecWhite** [EnigmaticaModpacks/Enigmatica8#351]
### Modpack Version

2.5.0

### Describe your issue.

The new JAMD mining dimension doesn't generate ores after updating the modpack. 
And as per the [suggestion](https://github.com/EnigmaticaModpacks/Enigmatica8/issues/336) I don't think this is the intended behaviour.

### Latest Log

https://gist.github.com/AlecWhite/fab5695b312e03e0aa4f2b7a6825ca33

### Have you modified the modpack?

Yes

### User Modifications

Added Rubidium and Rubidium Extras.

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NielsPilgaard** [comment]
Thank you for the report, we will investigate the issue.

**Comment by NielsPilgaard** [comment]
This is.. super strange. I was expecting it to work out of the box 😄

**Comment by AlecWhite** [comment]
It seems to be a problem with [TerraBlender](https://github.com/nanite/JAMD/issues/2). 
And [the solution seems to be](https://github.com/Glitchfiend/TerraBlender/issues/94) to downgrade from TerraBlender 1.2.0.126 to 1.1.0.102.
I did it and now JAMD works .

**Comment by AlecWhite** [comment]
Whoops accidentally closed it.

**Comment by NielsPilgaard** [comment]
Oh, great! Thanks for doing the work :D
