### ISSUE TITLE
rubidium breaking chunk render?

### ISSUE THREAD

**Issue by joinmod** [EnigmaticaModpacks/Enigmatica8#356]
### Modpack Version

2.5.1

### Describe your issue.

upon loading into world with rubidium game will crash no matter what i will try
but if i load into world first and then enable rubidium, chunks will be glitching like invis blocks or random chunked textures in sky by log i cant tell what happening or witch mod causing that

additional info:
java: BellSoft LibericaJRE 17 Full

JVM: -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true

### Crash Report

https://gist.github.com/joinmod/d0dcd465950d47dfc2cc99f243e6e125

### Latest Log

https://gist.github.com/joinmod/fa93df7b73bcddc9fd1564cf9f72d5bf

### Have you modified the modpack?

Yes

### User Modifications

rubidium 0.5.5 (only this causing crash and also, i did turned off other my mods below)
rubidium extra 0.4.17
oculus 1.5.2
rubidium dynamic lights 1.3.3
texturesrubidiumOptions 1.0.4

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by embeddedt** [comment]
Try running without Oculus.

**Comment by joinmod** [comment]
If will you read, you will see what i already did that 
I disable every my mods except rubidium

**Comment by NielsPilgaard** [comment]
There's a reason Rubidium isn't in the pack, we can't really help you :)
