### ISSUE TITLE
AE Infinity Range Card

### ISSUE THREAD

**Issue by NickyMB** [EnigmaticaModpacks/Enigmatica8#357]
### Modpack Version

2.5.1

### Describe your issue.

Infinity Range Card does not work when I'm in a compact machine

### Have you modified the modpack?

Yes

### User Modifications

Added Draconic Evolution

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Szef#2794

**Comment by NickyMB** [comment]
it also doesn't work in nether

**Comment by NielsPilgaard** [comment]
Did you chunkload your AE network?

**Comment by NickyMB** [comment]
Yes, using ftb maps

**Comment by NickyMB** [comment]
My bad i was using infinity card not dimension card
