### ISSUE TITLE
Minecraft Exit Code Error: exit code -805306369

### ISSUE THREAD

**Issue by NickyMB** [EnigmaticaModpacks/Enigmatica8#360]
### Modpack Version

2.5.1

### Describe your issue.

Stuck on loading terrain after a while app does not respond and shuts down with exit code exit code -805306369.

### Latest Log

<script src="https://gist.github.com/NickyMB/e4a3a906aebb19d8032a26afb586f821.js"></script>

### Have you modified the modpack?

Yes

### User Modifications

Added mods:
Draconic Evolution
Brandons core
LazierAE2
PackagedAuto

### Did the issue happen in singleplayer or on a server?

Singleplayer

### Discord Username

Szef#2794

**Comment by NickyMB** [comment]
<script src="https://gist.github.com/NickyMB/ff4b88b82f859241a28a6642db833e3b.js">latest.log</script>
<script src="https://gist.github.com/NickyMB/989edf3ada78c6216cb5db89c422192f.js">crash-2023-04-13_15.35.19-server.txt
</script>

**Comment by NickyMB** [comment]
idk if how to do it properly 
https://gist.github.com/NickyMB/989edf3ada78c6216cb5db89c422192f
https://gist.github.com/NickyMB/ff4b88b82f859241a28a6642db833e3b

**Comment by NielsPilgaard** [comment]
The gist links are perfect, thanks 👍 

Please try deleting the config `Mekanism/generators.toml`

**Comment by NickyMB** [comment]
Thanks, it worked. I was afraid that i lost my world <3
