### ISSUE TITLE
Create chunkloader

### ISSUE THREAD

**Issue by 0xicl33n** [EnigmaticaModpacks/Enigmatica8#38]
### URL

https://www.curseforge.com/minecraft/mc-mods/create-chunkloading

### Why would you like the mod added?

This mod adds a chunk loader that works with create contraptions like trains or mining rigs.

**Comment by NillerMedDild** [comment]
Iirc this functionality was not added to Create itself because it caused too many issues. I think it's too risky to add unfortunately.

**Comment by User-12691296** [comment]
This seems unnecessary... Vanilla has a (now intentional as of 1.16) chunkloader, the 3x3 of chunks around a nether portal are loaded for 15 seconds when an entity passes through them. Keep an item going back and forth, and you've got infinite chunk loading in the nether and overworld. For the end dimension, Ender Dragons keep the 15x15 area of chunks around them loaded at all times

**Comment by theboo** [comment]
It's less about the chunk loading itself, heck we give 25 free force loaded chunks through FTB... And there is multiple other chunkloaders in the pack.. What niller is talking about is issues with moving chunkloaders, chunkloaders on a minecart contraptions etc

**Comment by 0xicl33n** [comment]
> This seems unnecessary... Vanilla has a (now intentional as of 1.16) chunkloader, the 3x3 of chunks around a nether portal are loaded for 15 seconds when an entity passes through them. Keep an item going back and forth, and you've got infinite chunk loading in the nether and overworld. For the end dimension, Ender Dragons keep the 15x15 area of chunks around them loaded at all times

Server software does NOT like to play nicely with nether portal chunk loaders. The entity ticks can have a large impact on low spec servers.. so setting up a chain of chunk loaded portals is just a bad idea in general. Personally, I do not allow my users to build them on vanilla. Not everyone can have hermitcraft specs
