### ISSUE TITLE
ore-excavation as FTB ULTMINE alternative

### ISSUE THREAD

**Issue by JayOlino** [EnigmaticaModpacks/Enigmatica8#39]
### URL

https://www.curseforge.com/minecraft/mc-mods/ore-excavation

### Why would you like the mod added?

Because of E6 I'am little spoiled :)

**Comment by TemperedFool** [comment]
This is a little unclear - what would be the advantage of switching?

**Comment by theboo** [comment]
Ultimine isn't out for 1.18 yet, I think they just want something to tide them over until ultimine comes

**Comment by TemperedFool** [comment]
Man it gets confusing having both issue trackers in the GitHub channel...

**Comment by NillerMedDild** [comment]
I'd prefer to wait for Ultimine tbh, unless it's a long way out.
