### ISSUE TITLE
Sushi Go Crafting

### ISSUE THREAD

**Issue by Buuz135** [EnigmaticaModpacks/Enigmatica8#42]
### URL

https://www.curseforge.com/minecraft/mc-mods/sushigocrafting/files/3609503

### Why would you like the mod added?

Very neat food mod

**Comment by Oskar6366** [comment]
Great, now I cannot create mechanical belts because kelp doesn't spawn.

**Comment by mcilhargey** [comment]
Kelp most certainly still spawns

**Comment by User-12691296** [comment]
Water bees. Get a manual centrifuge and find an oceannic bee nest, put a camp fire under it and shear it. Put the combs and some glass bottles in the manual centrifuge, shift+right click, and get tons of kelp. I have two stacks without finding a single naturally spawning one. And it's very farmable after you get your first one
