### ISSUE TITLE
Tetra Tools Compatibility

### ISSUE THREAD

**Issue by eliminat** [EnigmaticaModpacks/Enigmatica8#43]
### Modpack Version

1.0.4

### Describe your issue.

Tetra pickaxe with steel and iron pickaxe heads is not always registering as an "Iron pickaxe" when attempting to harvest ores, such as harvesting Nickel or Redstone ores.

Supplementaries enchanted books also aren't accepted as enchanted books for applying to tetra tools.

### Have you modified the modpack?

Yes

### User Modifications

Updated Supplementaries to 1.1.9

### Did the issue happen in singleplayer or on a server?

Server

**Comment by mickelus** [comment]
That's working as intended. You need an iron tier pickaxe to harvest redstone, unless you're running the same pickaxe head on both sides you get -1 to harvest tier.

**Comment by NillerMedDild** [comment]
That seems counterintuitive tbh, if they're the same mining level surely they shouldn't have a level deducted?

**Comment by mickelus** [comment]
It's not intuitive that two pickaxe heads with the same tier would give a +1 synergy either, but it would be difficult to explain in a datadriven fashion, would require a significantly more complex synergy system and a complete rework of the synergy indicator tooltip. There's more to it, but I'm not sure if there's a need to dive deeper.

**Comment by NillerMedDild** [comment]
Fair enough.

What about the other part of the issue? 😀

**Comment by mickelus** [comment]
Also intended behaviour, from the supplementaries wiki:
> Stasis is a new enchantment just for slingshot and can be found in end cities

**Comment by NillerMedDild** [comment]
Ah alright ^^' thanks!
