### ISSUE TITLE
Supplementaries enchanted books for vanilla enchants unusable in Tetra Tools

### ISSUE THREAD

**Issue by eliminat** [EnigmaticaModpacks/Enigmatica8#44]
The previous issue was closed, but uncertain about the answer to Supplementaries enchanted books.

From the previous issue:
Also intended behaviour, from the supplementaries wiki:
> Stasis is a new enchantment just for slingshot and can be found in end cities

_Originally posted by @mickelus in https://github.com/EnigmaticaModpacks/Enigmatica8/issues/43#issuecomment-1018417793_

However, I am not attempting a Supplementaries enchantment. I've tried Sharpness 3 for my swords, Power V for my bow, etc. These are vanilla enchants, but Supplementaries replaces the books with its own. These are created by enchanting books in the vanilla enchanting table, so unsure how to get vanilla enchanted books to use on the tetra tool if Supplementaries replaces them.

The tag is Supplemenatries:Placeable_Books

If this is still intended, we need a way to convert them back to an identical vanilla enchanted book.

![image](https://user-images.githubusercontent.com/7636368/150549798-0bfebfe3-e8ee-4b25-8d83-154c30c6ed28.png)
![image](https://user-images.githubusercontent.com/7636368/150549825-2961e2db-0746-4c3a-927b-6638ccbc3812.png)
![image](https://user-images.githubusercontent.com/7636368/150549863-2d602dda-09ed-42f3-817c-3b887edecb55.png)
![image](https://user-images.githubusercontent.com/7636368/150549899-b34d778b-2213-4b00-84f1-c06af13e135f.png)

**Comment by Darkere** [comment]
The books is still the vanilla book. it just has the supplementaries:placeable_book tag.

**Comment by eliminat** [comment]
That's what I thought, but it's texture/image changes based on the type of enchant, and in Tetra gives the message "The provided Material cannot be used for this schematic." This is not an integrity, or magic limit issue as I would expect, it just doesn't seem to recognize the book as an enchanted book.
If i use a book that remains vanilla (no appearance change) it applies to the tetra tool no issue.

**Comment by mickelus** [comment]
Still working on the enchantment revamp so it doesn't have proper tooltips for all error states yet, but it looks like you already have a sharpness enchantment on that sword so it's not going to let you apply another.
