### ISSUE TITLE
LootJS

### ISSUE THREAD

**Issue by DAmNRelentless** [EnigmaticaModpacks/Enigmatica8#48]
### URL

https://www.curseforge.com/minecraft/mc-mods/lootjs-forge

### Why would you like the mod added?

There is no concrete use-case for the players but I wanted to show you the mod and its possibilities for your pack developers.

LootJS is an add-on for KubeJS and allows you to heavily modify all kinds of loot-related things with JS-Scripts. Removing, adding and replacing drops is all possible. You can define a lot of conditions such as random chances, structure requirements, etc.
We know there are a lot of pack developers who tried to find something like this in the past because they wanted to remove certain drops or modify loot.

Wiki with examples and docs, can all be found on the linked GitHub.
Hope that's helpful for future development of nice modpacks. It supports 1.16 and 1.18.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, looks like a great mod! I'll keep it in mind the next time we have to tinker with loot tables. 
Excellent documentation 👌

**Comment by NielsPilgaard** [comment]
We have no need for this at the moment :)
