### ISSUE TITLE
Block Particle Issue

### ISSUE THREAD

**Issue by TheShatterbird** [EnigmaticaModpacks/Enigmatica8#5]
### Modpack Version

1.0.1

### Describe your issue.

When you break a block and the particles from such are still visible, picking up the item that was dropped causes the particles to turn black (hard to screenshot because of how short it is, but it's kinda jarring)
![2021-12-05_16 42 01](https://user-images.githubusercontent.com/95345953/144768469-34e699e3-ac66-4853-8d91-220833153cae.png)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by TheShatterbird** [comment]
Additional info discovered, this happens for *any* block particles currently visible whenever you pick an item up.

**Comment by NillerMedDild** [comment]
Thanks for the report. I'm unable to reproduce this in-dev, perhaps a mod update has fixed it :)

**Comment by ochotonida** [comment]
Seems to be related to this forge issue: https://github.com/MinecraftForge/MinecraftForge/issues/8221

**Comment by TheShatterbird** [comment]
That seems very likely, the actual effect of it changes when I restarted the modpack, it went from block drops to the critical particles when you picked up mob drops, which was rather odd. No ideas for what causes it really
