### ISSUE TITLE
Netty Handler Exception - Reaching out

### ISSUE THREAD

**Issue by MrBrebby** [EnigmaticaModpacks/Enigmatica8#51]
### Modpack Version

1.0.4

### Describe your issue.

I do not expect this to gain any traction here.  I have been researching this issue for a bit and finally someone has posted on the Forge Forum.  However, when playing this modpack, and it seems other Forge based modpacks are running in a LAN environment; no players can join.  Any player will receive this message:

internal exception: io.nettyhandler.codec.endcoderexception:io.netty.util.illegalreferencecountexceptionl refcnt: 0

There has been little information as to a resolution to this; other than port forwarding my public IP address, using a NAT Hairpin and let my wife join my game through my public IP address instead of my internal one as to be expected in a LAN connection.

Does anyone have any information that may resolve this and allow us to finally play the damn modpack we have been waiting for.  (Apparently this is a well known issue among all Forge based Modpacks running 1.18.1 - I am sure the Forge Devs are looking into it, but I figured I would ask here in case.)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by theboo** [comment]
well first of all, there is some info on your issue here, nothing you can do really: https://github.com/MinecraftForge/MinecraftForge/issues/8377

2nd: another option for you would be to just run a server on the same PC you play on if you can.

**Comment by NillerMedDild** [comment]
Looks like a fix is imminent in Forge, maybe even available now 😀

**Comment by NillerMedDild** [comment]
Should be fixed in Forge `1.18.1-39.0.60` :D

**Comment by MrBrebby** [comment]
Well shit............thanks for keeping on top of this.  Glad that I reached out here.

Wealth of knowledge from you guys.  Thanks a bunch.
