### ISSUE TITLE
Cannot start server: "win_args.txt" cannot be found or load 

### ISSUE THREAD

**Issue by Monaxika** [EnigmaticaModpacks/Enigmatica8#52]
### Modpack Version

Enigmatica8Server-1.0.4

### Describe your issue.

Hi there,
I tried to set up a server by following the instructions from the "Installing a server"-Guide. Download etc. worked, but the server cannot start because the is an issue with the "win_args.txt"-file. I already looked for it - it is at the shown path. Of course I don't know, how it has to look like "inside". 

What can I do? =)

Thanks for your help! 

![Enigmatica8Server_issue](https://user-images.githubusercontent.com/98641986/151656812-0a34a384-a255-48e1-b8f2-c67e9502918d.JPG)

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report - Which operating system are you on? :)

**Comment by Monaxika** [comment]
Hi, I'm using Windows 10, Version 21H2

**Comment by NillerMedDild** [comment]
Try deleting the file `serverstarter.lock` and run the start-server.bat again :)

**Comment by Monaxika** [comment]
Did it, still the same thing. :S

![Enigmatica8Server_issue2](https://user-images.githubusercontent.com/98641986/151658322-44f036c7-1432-46f2-8e9f-89730fa40985.JPG)

**Comment by NillerMedDild** [comment]
Hmm odd, could you please upload your win_args file here?

**Comment by Monaxika** [comment]
If it is of interest: the filepath is exactly the same as in the error message above and I didn't change a thing here...

[win_args.txt](https://github.com/EnigmaticaModpacks/Enigmatica8/files/7963528/win_args.txt)

**Comment by NillerMedDild** [comment]
Aha! Are you using Java 17?

**Comment by Monaxika** [comment]
I thought I was, but after reinstalling it looks a lot better now. "Preparing spawning area" is loading. So thank you so much for the quick answer (and sorry for the stupid, selfmade problem ^^')

**Comment by NillerMedDild** [comment]
No problem at all, I did the same thing with my first 1.18 server :P

**Comment by Night3105** [comment]
hello i have the same problem but with the unix_args.tkt file 
[unix_args.txt](https://github.com/EnigmaticaModpacks/Enigmatica8/files/9803909/unix_args.txt)

Thanks for your help!
