### ISSUE TITLE
Trying My Luck - Mob Grinding Utils

### ISSUE THREAD

**Issue by MrBrebby** [EnigmaticaModpacks/Enigmatica8#54]
### URL

https://www.curseforge.com/minecraft/mc-mods/mob-grinding-utils

### Why would you like the mod added?

Don't know when Mekanism is going to be ported over to 1.18.

And the XP Tap is so damn fun to use.

I know you aren't interested in adding "random ass" mods to the mix, and that's understandable; just wondering if there was space for this guy.

**Comment by NillerMedDild** [comment]
I'll think about it :)

**Comment by NillerMedDild** [comment]
Sorry but no, I'd rather get these same features from mods that I would include anyway :)
Except the XP Tap, that will be missed.

**Comment by MrBrebby** [comment]
¯\_(ツ)_/¯
Gave it a shot.  Still the best Modpack I have played.
