### ISSUE TITLE
[Applied Energistics 2] Certus Dust and Fluix Dust recipe missing

### ISSUE THREAD

**Issue by gagnonj** [EnigmaticaModpacks/Enigmatica8#55]
### Modpack Version

1.0.4

### Describe your issue.

For AE2's dusts, there doesn't appear to be a way to grind the dust down from crystals. Nothing appears in JEI and no known crushers seem to work. The Quartz Grindstone from AE2 also appears to have been removed?

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by NillerMedDild** [comment]
Thank you for the report, I will investigate the issue.

**Comment by Technici4n** [comment]
There should be such recipes in AE2 itself in 10.0.1: https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/6015.
