### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by sid-marie** [EnigmaticaModpacks/Enigmatica8#60]
### Modpack Version

1.0.5

### Describe your issue.

I am constantly crashing.

### Crash Report

https://gist.github.com/sid-marie/f1f55d1e3ef878c2ea7891750b11c6e1

### Latest Log

https://gist.github.com/sid-marie/751673e328cc486a64516a20b65c42d0

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report. Have you tried reinstalling? :)
