### ISSUE TITLE
crashing still

### ISSUE THREAD

**Issue by sid-marie** [EnigmaticaModpacks/Enigmatica8#62]
### Modpack Version

1.0.5

### Describe your issue.

I'm still crashing but not as much. I reinstalled and it worked for a few hours then crashed and it kept happening. Is there something I am doing? 

Thank you so much for your help.

### Latest Log

https://gist.github.com/sid-marie/8208b78372da8053c26f9ddd77d49c01

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Thanks for the report. You appear to have linked your debug.log, could you please provide crash report and/or latest.log instead? :)

**Comment by sid-marie** [comment]
I think this is the right one. It is from today when it crashed. I can’t find any crash reports. The last one is from January and that was the last version. I don’t know whether it is my laptop or not.

https://gist.github.com/sid-marie/db14c67113cd4fbda223b29defe1af13#file-gistfile1-txt

Thank you by the way for the help.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by NillerMedDild** [comment]
That's still a debug.log and doesn't have a crash in it :/

**Comment by sid-marie** [comment]
Hi,

I just wanted to let you know that I reinstalled it and started a world on 1.0.4 and it has not crashed nearly as much as 1.0.5.

Again thank you for the help


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
