### ISSUE TITLE
Vanilla Excavators

### ISSUE THREAD

**Issue by HeroOfTheWinds** [EnigmaticaModpacks/Enigmatica8#63]
### URL

https://www.curseforge.com/minecraft/mc-mods/vanilla-excavators-forge

### Why would you like the mod added?

Excavators are very useful for levelling/clearing large areas of soft material quickly, and these perfectly complement the Vanilla Hammers mod already in the pack.  (In fact, they are from the same author!)

**Comment by NillerMedDild** [comment]
Now that we have Tinkers I don't think there's any need for this mod :)
