### ISSUE TITLE
Switch biome mods

### ISSUE THREAD

**Issue by Halfdeaf** [EnigmaticaModpacks/Enigmatica8#64]
### URL

https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-youll-go

### Why would you like the mod added?

I think it's high time to switch to OH the biomes you'll go. It's been getting steady updates and has enough content to switch.

**Comment by NillerMedDild** [comment]
Does it have biomes now? 😄

**Comment by MrBrebby** [comment]
Dunno, kinda loving the Biomes O'Plenty - Underground Crystal Caves/Glowshroom caves have been a nice addition to my lush cave.

**Comment by NielsPilgaard** [comment]
I'm gonna try testing with both, see how that goes :)

**Comment by NielsPilgaard** [comment]
I found BoP to be a bit lackluster compared to BYG tbf, so we're gonna switch in v2.0.0

**Comment by MrBrebby** [comment]
Gotta do whats best for the modpack.

I am curious if it will affect my seed - given I found a nice lush cave, with not much of anything else regarding Biomes O Plenty.

**Comment by NielsPilgaard** [comment]
I think it will 🤔

**Comment by MrBrebby** [comment]
/shrug

It is what it is.
