### ISSUE TITLE
To go alongside a switch to BYG

### ISSUE THREAD

**Issue by Halfdeaf** [EnigmaticaModpacks/Enigmatica8#65]
### URL

https://www.curseforge.com/minecraft/mc-mods/variant16x-biomesyougo

### Why would you like the mod added?

A compilation of complimentary mods to Oh the biomes you'll go.

https://www.curseforge.com/minecraft/mc-mods/macaws-bridges-oh-the-biomes-youll-go

https://www.curseforge.com/minecraft/mc-mods/macaws-roofs-oh-the-biomes-youll-go

**Comment by NielsPilgaard** [comment]
Variant16x BYG is not for 1.18 sadly, the others I've added 👍
