### ISSUE TITLE
Bug/Suggestion Sushi Go replaces some Kelp with Seaweed and Create has a belt recipe with dried Kelp.

### ISSUE THREAD

**Issue by Oskar6366** [EnigmaticaModpacks/Enigmatica8#69]
### Modpack Version

1.0.5

### Describe your issue.

When I created a server with this modpack all of the kelp in a few thousound block radius that I checked has been turned into seaweed that I cannot process the same way as kelp.
Both can be dried, so kelp can be made into dried kelp and seaweed into dried seaweed:
The problem is with the mechanical belt recipe from Create, it requires DRIED KELP, which I cannot find for miles.
I value the Create mod much more over the Sushi stuff so I think it's an issue.
Maybe it's a biome problem too, because when I created a world in singeplayer I could find kelp and seaweed mixed, yet I use the same version. Only difference I can see are the biomes I'm in.

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Both

**Comment by Oskar6366** [comment]
Update:
It seems that Lukewarm Oceans have mixed kelp and seaweed, while Warm Oceans have only Seaweed.

**Comment by NillerMedDild** [comment]
We'll change the belt recipe to accept both 👍

**Comment by NielsPilgaard** [comment]
Sorry it took a bazillion days, it's in next release :P
