### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by RRFreitas** [EnigmaticaModpacks/Enigmatica8#70]
### Modpack Version

1.0.4

### Describe your issue.

I was playing normally yesterday, and today this crash is happening :confused:

### Crash Report

https://gist.github.com/RRFreitas/18f17f137ae01ccc37fb695677a4d442

### Latest Log

https://gist.github.com/RRFreitas/e825b8b9e983568e2e4f473fb762e60b

### Have you modified the modpack?

Yes

### User Modifications

Added optifine 1.18.1_HD_U_H4

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by Darkere** [comment]
try reinstalling
