### ISSUE TITLE
FTB Teams

### ISSUE THREAD

**Issue by panzeson** [EnigmaticaModpacks/Enigmatica8#73]
### URL

https://www.curseforge.com/minecraft/mc-mods/ftb-teams-forge#:~:text=Library%20for%20mods%20that%20can,need%20to%20whitelist%20them%20otherwise.

### Why would you like the mod added?

Couldn't link both the FTB Chunks and FTB Teams mod at once (Haven't tried, but I assume you can't), but this would also be nice to have.

**Comment by NillerMedDild** [comment]
This is already in 1.0.5 :)
