### ISSUE TITLE
BetterFurnaces

### ISSUE THREAD

**Issue by panzeson** [EnigmaticaModpacks/Enigmatica8#78]
### URL

https://www.curseforge.com/minecraft/mc-mods/better-furnaces-reforged

### Why would you like the mod added?

Again, just throwing ideas out there. This probably makes endgame in the future a little too easy and I know there are already some slightly faster furnaces, but this one takes the cake when it comes to fast furnaces.

There's also a addon to this mod called Ultimate Furnaces, linked here: https://www.curseforge.com/minecraft/mc-mods/ultimate-furnaces-bfr/

Again, just throwing them ideas out there, I'm not expecting all of them to get accepted, just want your thoughts on them as I play the pack.

**Comment by NillerMedDild** [comment]
Thanks for the suggestion.

I dislike this mod tbh, I think it's a boring way to achieve faster smelting.
