### ISSUE TITLE
More Minecarts Mod

### ISSUE THREAD

**Issue by panzeson** [EnigmaticaModpacks/Enigmatica8#79]
### URL

https://www.curseforge.com/minecraft/mc-mods/more-minecarts

### Why would you like the mod added?

Pretty nifty mod with a lot of minecart options and contraptions. I saw this being used in a video ChosenArchitect made in a Create video where he used it in combination with the Create mod, I feel like it'd provide a certain level of fun automation!

**Comment by NillerMedDild** [comment]
Thanks for the suggestion, I'll have a look in-game :)
