### ISSUE TITLE
OpenBlocks Elevator Mod has a 1.18.1 beta!

### ISSUE THREAD

**Issue by qMatriiix** [EnigmaticaModpacks/Enigmatica8#80]
### URL

https://www.curseforge.com/minecraft/mc-mods/openblocks-elevator/files

### Why would you like the mod added?

This is just a huge QoL mod. Makes building layers of a base super convenient (especially with the new world heights and depths)!

I know y'all had it in E6 and assume it wasn't added originally due to no port for 1.18.1 yet. Wanted to put this out there to hopefully get it in the next update!

**Comment by NillerMedDild** [comment]
Use a Travel Anchor instead, they provide the same functionality and more :)
