### ISSUE TITLE
crashed

### ISSUE THREAD

**Issue by sid-marie** [EnigmaticaModpacks/Enigmatica8#81]
### Modpack Version

1.0.5

### Describe your issue.

Crashed when I tried opening. Also is this the right spot to post these?

### Crash Report

https://gist.github.com/sid-marie/e7371c0e82fa43b99274e9eda71472b2#file-gistfile1-txt

### Latest Log

https://gist.github.com/sid-marie/a3db23a47c308dbaa7ec1f485c4ebe7b#file-gistfile1-txt

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Singleplayer

**Comment by NillerMedDild** [comment]
Usually this kind of issue is best to report on Discord, but it's fine 🙂
It looks like something went wrong with your instance, I'm guessing you have several versions of the same mod in your mods folder. The CurseForge app doesn't remove old mods when updating at the moment 😅
You can either redownload the pack or remove the extra files from your mods folder.

I'm gonna tag this as support but feel free to continue here if you have questions.
