### ISSUE TITLE
Create: Crafts & Additions

### ISSUE THREAD

**Issue by panzeson** [EnigmaticaModpacks/Enigmatica8#82]
### URL

https://www.curseforge.com/minecraft/mc-mods/createaddition

### Why would you like the mod added?

It supports compatibility and recipe integrations from AE2, Immersive Engineering, and CC as well as providing alternative ways of powering Create contraptions! 

> Added Compatibility & Integration:
> - Recipe compatibility with Simple Jetpacks 2 (Electric Jetpacks).
> - Recipe compatibility with Immersive Engineering (External Heater, Lapis Sheet pressing, Sphalerite mineral deposit, Alloys, Treated Wood).
> - Recipe compatibility with Mekanism (Rose Quartz Enriching & Metallurgic Infusing).
> - Recipe compatibility with Tinkers Construct (Alloys).
> - Recipe compatibility with Applied Energistics 2, the Tesla Coil can be used to charge Certus Quartz.
> - Integration with ComputerCraft, the Electric Motor can be used as a peripheral ([See API](https://github.com/mrh0/createaddition/blob/main/COMPUTERCRAFT.md))

**Comment by NillerMedDild** [comment]
Thanks for the report.

I'm not gonna add this, for the same reason I wouldn't add it to E6 :)
https://github.com/EnigmaticaModpacks/Enigmatica6/discussions/1190
