### ISSUE TITLE
Vanilla AIOTs 

### ISSUE THREAD

**Issue by MelanX** [EnigmaticaModpacks/Enigmatica8#83]
### URL

https://www.curseforge.com/minecraft/mc-mods/vanilla-aiots/files

### Why would you like the mod added?

Enigmatica 6 contains AIOT Botania which is used a lot by some users. The tools here are made with Vanilla tools. I think, a lot of users who liked the AIOTs by AIOT Botania would use and like these AIOTs, too.

**Comment by NillerMedDild** [comment]
I'm a bit on the fence on this one tbh, I generally think AIOTs are a bit too powerful, I think they're fine with Botania materials only because they require a bit more effort to obtain. I'll mow it over :)

**Comment by MelanX** [comment]
You could configure the speed, attack damage bonus, harvest level, and enchantment value for each material if you want. This would make it to a weapon which deals less damage and is a bit slower if you want. 
Additionally, you can configure the durability modifier. This means: It's not the 5 * 1561 for each diamond AIOT but only 2 * 1561 if you want. That makes them less efficient in the cost compared to all tools.

I can still understand your thoughts :)

**Comment by NielsPilgaard** [comment]
Given the focus of E8 is now meant to be adventure and exploration, I think having the option for AIOTs suits it fairly well, added 👍
