### ISSUE TITLE
JourneyMaps Integration

### ISSUE THREAD

**Issue by panzeson** [EnigmaticaModpacks/Enigmatica8#84]
### URL

https://www.curseforge.com/minecraft/mc-mods/journeymap-integration

### Why would you like the mod added?

I just saw this while browsing through the mods list, would be a pretty cool addition for the mods that are already present in the modpack like Waystones, Immersive Engineering, and FTB Chunks, etc.

**Comment by MarkoBogSrb** [comment]
+1
