### ISSUE TITLE
Additional Additions

### ISSUE THREAD

**Issue by panzeson** [EnigmaticaModpacks/Enigmatica8#87]
### URL

https://www.curseforge.com/minecraft/mc-mods/additional-additions-forge

### Why would you like the mod added?

Adds in a couple of cool stuff like rose gold materials, gilded netherite for those that visit the nether often, amethyst lamps that prevent mob spawns in a 8 block radius, and more.

**Comment by NillerMedDild** [comment]
Looks pretty cool, but I'm generally not a fan of mods that add seemingly random items, they tend to have many bugs 😬
I'll think about it.

**Comment by panzeson** [comment]
> 

Honestly the only good thing I find pretty cool in the mod is the amethyst lamp and the gold plating on the netherite and its effect.

A smaller and less random alternative could be this mod: https://www.curseforge.com/minecraft/mc-mods/advanced-netherite that adds more tiers of netherite
