### ISSUE TITLE
[Mod] Beyond Earth

### ISSUE THREAD

**Issue by CheetahCyberBoi** [EnigmaticaModpacks/Enigmatica8#90]
### URL

https://www.curseforge.com/minecraft/mc-mods/beyond-earth

### Why would you like the mod added?

This mod got updated to 1.18 and is a great space mod for newer versions. It is easily integrated into other mods, and has a nice selection of planets.

**Comment by NillerMedDild** [comment]
I'll think about it :)

**Comment by NielsPilgaard** [comment]
Beyond Earth looks like a complete rip-off of GalactiCraft to be honest, I'd rather not have it in Enigmatica.
