### ISSUE TITLE
Simple Backups

### ISSUE THREAD

**Issue by MelanX** [EnigmaticaModpacks/Enigmatica8#92]
### URL

https://www.curseforge.com/minecraft/mc-mods/simple-backups

### Why would you like the mod added?

It's always good to have a proper backup. Since FTB Backups isn't updated yet, and there is no other backups mod for 1.18, I made this one. You could also wait for FTB Backups or leave the decision to add a backup mod at the player/server owner.

**Comment by NillerMedDild** [comment]
Thank you kindly! I'll add it unless FTB Backups updates before release of next update 😄
