### ISSUE TITLE
Some Assembly Required

### ISSUE THREAD

**Issue by ochotonida** [EnigmaticaModpacks/Enigmatica8#95]
### URL

https://www.curseforge.com/minecraft/mc-mods/some-assembly-required

### Why would you like the mod added?

Some Assembly Required allows players to create custom sandwiches. It's pretty similar to Culinary Construct (which is already in the pack), but there are some key differences, such as the ability to automatically make sandwiches using Create and the ability to place down sandwiches.
Having both Culinary Construct and Some Assembly Required in the same pack is probably a bit much, but I thought I'd suggest anyway in case people prefer this mod.

**Comment by NillerMedDild** [comment]
Hmm I think I'll swap them in a major update, if I like your take better 🤔

**Comment by JoaGamo** [comment]
+1 for Create Assembly sandwich, the culinary construct is boring
