### ISSUE TITLE
Refined Storage/Sophisticated Backpacks

### ISSUE THREAD

**Issue by qCastor** [EnigmaticaModpacks/Enigmatica8#96]
### Modpack Version

1.0.5

### Describe your issue.

I have liquid experience being pumped with a magnet/tank backpack from my farm into my Refined storage. It all imports fine and shows up in the fluid grid, BUT there is no way of retrieving that experience from storage. I thought of pumping it back into another backpack with the Advanced experience pump which allows a player to get xp from the tank, but I then realized that I cannot set the exporter filter because there are no buckets of xp or any recipes at all with sophisticated backpack's liquid experience. 

I'm not sure if this issue is more suited for the mod creators or something that you all could look into with maybe another mod that adds buckets of experience. 

Thanks!

### Have you modified the modpack?

No

### Did the issue happen in singleplayer or on a server?

Server

**Comment by NillerMedDild** [comment]
Thanks for the report, I found it on the mods tracker as well here: https://github.com/P3pp3rF1y/SophisticatedBackpacks/issues/427 :)

**Comment by meheruuuuuuuuuuuuuu** [comment]
The Fluid Interface can be right-clicked with a backpack in the GUI.
I succeeded in specifying a liquid experience that way.

**Comment by qCastor** [comment]
> 

This worked! I can import to my backpack and withdraw with the xp pump. Thanks!!

**Comment by P3pp3rF1y** [comment]
You can also just simply drag the experience fluid into exporter filter from JEI
