### ISSUE TITLE
Mystical Agriculture

### ISSUE THREAD

**Issue by come1on** [EnigmaticaModpacks/Enigmatica8#99]
### URL

https://www.curseforge.com/minecraft/mc-mods/mystical-agriculture

### Why would you like the mod added?

It is a fine additon to the mod pack.
It is also compatible with other mods like Create.

**Comment by Shoesington** [comment]
I'm gonna counterpoint beg for this to not be added. It literally destroys half of the title of the game by invalidating mining completely. It's grotesque and horrible and please no.

**Comment by MrBrebby** [comment]
I love this mod so much...........but i battled with suggesting this mod. And I agree with Shoesington.  It would detract a lot from this Modpack.

**Comment by NillerMedDild** [comment]
Sorry but no, for the reasons stated above 😄
